/* runtime_data.c — generated from src/parts/runtime.inc during the 2026-08 modularization. */
#include "s2c_all.h"

/* ================================================================== */
/* L10 Runtime library (emitted into output C file)                  */
/* ================================================================== */

const char *RT_HEADER =
"/* ---- shell2c runtime (deep optimization) ---- */\n"
"#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n"
"#include <stdint.h>\n#include <ctype.h>\n#include <unistd.h>\n#include <dirent.h>\n"
"#include <fcntl.h>\n#include <sys/stat.h>\n#include <sys/wait.h>\n"
"#include <sys/types.h>\n#include <errno.h>\n#include <time.h>\n"
"#include <malloc.h>\n#include <sys/mman.h>\n#include <pwd.h>\n#include <grp.h>\n#include <signal.h>\n#include <regex.h>\n"
"#include <sys/utsname.h>\n#include <sys/ioctl.h>\n#include <termios.h>\n"
"#include <glob.h>\n#include <fnmatch.h>\n#include <stdarg.h>\n"
"\n"
"static int __exit_status=0;\n"
"static int __sh_argc=0;\n"
"static char **__sh_args=NULL;\n"
"static char *__sh_pos_args[10]={NULL};\n"
"static int __sh_last_bg_pid=0;\n"
"static int __sh_set_e=0;\n"
"static int __sh_set_u=0;\n"
"static int __sh_set_x=0;\n"
"/* Bash special variables */\n"
"static int __sh_lineno=0;\n"
"static int __sh_pipestatus[16]={0};\n"
"static int __sh_shlvl=1;\n"
"static unsigned int __sh_rand_seed=0;\n"
"static time_t __sh_start_time=0;\n"
"/* __sh_getenv_special: resolve bash special vars (uses static buffer, no pool dependency) */\n"
"static const char *__sh_special_var(const char *name){\n"
"  static char __sv_buf[256];\n"
"  if(!strcmp(name,\"RANDOM\")){\n"
"    if(!__sh_rand_seed) __sh_rand_seed=(unsigned int)time(NULL)^(unsigned int)getpid();\n"
"    __sh_rand_seed=__sh_rand_seed*1103515245+12345;\n"
"    snprintf(__sv_buf,sizeof(__sv_buf),\"%d\",(__sh_rand_seed/65536)%32768); return __sv_buf;\n"
"  }\n"
"  if(!strcmp(name,\"SECONDS\")){\n"
"    snprintf(__sv_buf,sizeof(__sv_buf),\"%ld\",(long)(time(NULL)-__sh_start_time)); return __sv_buf;\n"
"  }\n"
"  if(!strcmp(name,\"LINENO\")){\n"
"    snprintf(__sv_buf,sizeof(__sv_buf),\"%d\",__sh_lineno); return __sv_buf;\n"
"  }\n"
"  if(!strcmp(name,\"BASHPID\")){\n"
"    snprintf(__sv_buf,sizeof(__sv_buf),\"%d\",(int)getpid()); return __sv_buf;\n"
"  }\n"
"  if(!strcmp(name,\"SHLVL\")){\n"
"    snprintf(__sv_buf,sizeof(__sv_buf),\"%d\",__sh_shlvl); return __sv_buf;\n"
"  }\n"
"  if(!strcmp(name,\"PIPESTATUS\")){ return \"0\"; }\n"
"  if(!strcmp(name,\"HOSTTYPE\")){\n"
"#if defined(__x86_64__) || defined(__amd64__)\n"
"    return \"x86_64\";\n"
"#elif defined(__aarch64__)\n"
"    return \"aarch64\";\n"
"#elif defined(__arm__)\n"
"    return \"arm\";\n"
"#else\n"
"    return \"unknown\";\n"
"#endif\n"
"  }\n"
"  if(!strcmp(name,\"OSTYPE\")){\n"
"#if defined(__linux__)\n"
"    return \"linux-gnu\";\n"
"#elif defined(__APPLE__)\n"
"    return \"darwin\";\n"
"#else\n"
"    return \"unknown\";\n"
"#endif\n"
"  }\n"
"  if(!strcmp(name,\"MACHTYPE\")){ return __sh_special_var(\"HOSTTYPE\"); }\n"
"  return NULL;\n"
"}\n"
"\n"
"/* ---- rotating buffer pools (safe for nested calls) ---- */\n"
"/* 4-slot pools: calling a function 4+ times in one expression still\n"
" * overwrites, but that's rare. 4 is the sweet spot for memory vs safety. */\n"
"static char __sh_indirect_p0[1024], __sh_indirect_p1[1024], __sh_indirect_p2[1024], __sh_indirect_p3[1024];\n"
"static int  __sh_indirect_i = 0;\n"
"static char __sh_substr_p0[4096], __sh_substr_p1[4096], __sh_substr_p2[4096], __sh_substr_p3[4096];\n"
"static int  __sh_substr_i = 0;\n"
"static char __sh_strip_p0[4096], __sh_strip_p1[4096], __sh_strip_p2[4096], __sh_strip_p3[4096];\n"
"static int  __sh_strip_i = 0;\n"
"static char __sh_replace_p0[4096], __sh_replace_p1[4096], __sh_replace_p2[4096], __sh_replace_p3[4096];\n"
"static int  __sh_replace_i = 0;\n"
"static char __sh_upper_p0[4096], __sh_upper_p1[4096], __sh_upper_p2[4096], __sh_upper_p3[4096];\n"
"static int  __sh_upper_i = 0;\n"
"static char __sh_lower_p0[4096], __sh_lower_p1[4096], __sh_lower_p2[4096], __sh_lower_p3[4096];\n"
"static int  __sh_lower_i = 0;\n"
"static char __sh_cmd_out_p0[65536], __sh_cmd_out_p1[65536], __sh_cmd_out_p2[65536], __sh_cmd_out_p3[65536];\n"
"static int  __sh_cmd_out_i = 0;\n"
"static char __sh_fmt_p0[8192], __sh_fmt_p1[8192], __sh_fmt_p2[8192], __sh_fmt_p3[8192];\n"
"static int  __sh_fmt_i = 0;\n"
"static char __sh_fn_out_p0[65536], __sh_fn_out_p1[65536], __sh_fn_out_p2[65536], __sh_fn_out_p3[65536];\n"
"static int  __sh_fn_out_i = 0;\n"
"static char __sh_arr_p0[8192], __sh_arr_p1[8192], __sh_arr_p2[8192], __sh_arr_p3[8192];\n"
"static int  __sh_arr_i = 0;\n"
"static char __sh_ps_p0[64], __sh_ps_p1[64], __sh_ps_p2[64], __sh_ps_p3[64];\n"
"static int  __sh_ps_i = 0;\n"
"\n"
"/* Helper: get next pool slot for a given base name */\n"
"static char *__sh_pool_next(char *p0, char *p1, char *p2, char *p3, int *idx){\n"
"  char *r = ( (*idx == 0) ? p0 : (*idx == 1) ? p1 : (*idx == 2) ? p2 : p3 );\n"
"  *idx = (*idx + 1) & 3;\n"
"  return r;\n"
"}\n"
"\n"
"/* ---- string helpers ---- */\n"
"static const char *__sh_indirect(const char *name){\n"
"  char *buf = __sh_pool_next(__sh_indirect_p0,__sh_indirect_p1,__sh_indirect_p2,__sh_indirect_p3,&__sh_indirect_i);\n"
"  char vn[256]; snprintf(vn,sizeof(vn),\"%s\",name);\n"
"  const char *v=getenv(vn); if(v) { snprintf(buf,1024,\"%s\",v); return buf; }\n"
"  buf[0]=0; return buf;\n"
"}\n"
"static const char *__sh_getenv(const char *name){\n"
"  const char *v=getenv(name); return v?v:\"\";\n"
"}\n"
"static const char *__sh_arr_join(const char **arr){\n"
"  char *buf = __sh_pool_next(__sh_arr_p0,__sh_arr_p1,__sh_arr_p2,__sh_arr_p3,&__sh_arr_i);\n"
"  buf[0]=0;\n"
"  for(int i=0;arr[i];i++){ if(i>0) strncat(buf,\" \",8192-strlen(buf)-1); strncat(buf,arr[i]?arr[i]:\"\",8192-strlen(buf)-1); }\n"
"  return buf;\n"
"}\n"
"/* Join function args (for $@ / $*) */\n"
"static const char *__sh_join_args(int argc, char **args){\n"
"  char *buf = __sh_pool_next(__sh_arr_p0,__sh_arr_p1,__sh_arr_p2,__sh_arr_p3,&__sh_arr_i);\n"
"  buf[0]=0;\n"
"  for(int i=0;i<argc;i++){ if(i>0) strncat(buf,\" \",8192-strlen(buf)-1); strncat(buf,args[i]?args[i]:\"\",8192-strlen(buf)-1); }\n"
"  return buf;\n"
"}\n"
"/* ${!#} — return last positional arg */\n"
"static const char *__sh_indirect_args(int argc, char **args){\n"
"  if(argc>=1 && args) return args[argc-1]?args[argc-1]:\"\";\n"
"  return \"\";\n"
"}\n"
"static int __sh_div_error = 0;\n"
"static char __sh_script_name[65536]=\"\";\n"
"static int __sh_safe_div_guard(void){ fprintf(stderr,\"division by 0\\n\"); __exit_status=1; return 1; }\n"
"static int __sh_safe_div(int a,int b,const char *expr,const char *token){ if(b==0){ fprintf(stderr,\"%s: line %d: %s: division by 0 (error token is \\\"%s\\\")\\n\",__sh_script_name[0]?__sh_script_name:\"shell2c\",__sh_lineno,expr?expr:\"0\",token?token:\"0\"); __exit_status=1; __sh_div_error=1; return 0; } return a/b; }\n"
"static int __sh_safe_mod(int a,int b,const char *expr,const char *token){ if(b==0){ fprintf(stderr,\"%s: line %d: %s: modulo by 0 (error token is \\\"%s\\\")\\n\",__sh_script_name[0]?__sh_script_name:\"shell2c\",__sh_lineno,expr?expr:\"0\",token?token:\"0\"); __exit_status=1; __sh_div_error=1; return 0; } return a%b; }\n"
"static int __sh_arr_count(const char **arr){\n"
"  int n=0; for(int i=0;i<256;i++) if(arr[i]) n++; return n;\n"
"}\n"
"/* BUG-10 fix: associative array helpers — store as key,value,key,value,... */\n"
"static const char *__sh_assoc_get(const char **arr,const char *key){\n"
"  for(int i=0;arr[i]&&arr[i+1];i+=2){ if(strcmp(arr[i],key)==0) return arr[i+1]; }\n"
"  return \"\";\n"
"}\n"
"static void __sh_assoc_set(const char **arr,const char *key,const char *val){\n"
"  for(int i=0;i<254;i+=2){\n"
"    if(!arr[i]){ arr[i]=strdup(key); arr[i+1]=strdup(val); return; }\n"
"    if(arr[i]&&strcmp(arr[i],key)==0){ free((void*)arr[i+1]); arr[i+1]=strdup(val); return; }\n"
"  }\n"
"}\n"
"static long __sh_pow(long base,long exp){\n"
"  if(exp<0) return 0;\n"
"  long r=1; while(exp-->0) r*=base; return r;\n"
"}\n"
"static int __sh_div_zero(const char *expr){\n"
"  fprintf(stderr,\"%s: line %d: %s: division by 0 (error token is \\\"0\\\")\\n\",__sh_script_name[0]?__sh_script_name:\"shell2c\",__sh_lineno,expr?expr:\"0\");\n"
"  __exit_status=1; __sh_div_error=1;\n"
"  return 0;\n"
"}\n"
"/* ${!arr[@]} — return space-separated list of array indices */\n"
"static const char *__sh_arr_indices(const char **arr){\n"
"  char *buf = __sh_pool_next(__sh_arr_p0,__sh_arr_p1,__sh_arr_p2,__sh_arr_p3,&__sh_arr_i);\n"
"  buf[0]=0; int first=1;\n"
"  for(int i=0;arr[i]&&i<256;i++){\n"
"    if(arr[i]){\n"
"      char num[16]; snprintf(num,sizeof(num),\"%d\",i);\n"
"      if(!first) strncat(buf,\" \",8192-strlen(buf)-1);\n"
"      strncat(buf,num,8192-strlen(buf)-1);\n"
"      first=0;\n"
"    }\n"
"  }\n"
"  return buf;\n"
"}\n"
"static const char *__sh_arr_slice(const char **arr,int off,int len){\n"
"  char *buf = __sh_pool_next(__sh_arr_p0,__sh_arr_p1,__sh_arr_p2,__sh_arr_p3,&__sh_arr_i);\n"
"  int n=0; while(arr[n]) n++;\n"
"  if(off<0) off+=n;\n"
"  if(off<0) off=0;\n"
"  if(off>n) off=n;\n"
"  int end=(len<0)?n:off+len; if(end>n) end=n;\n"
"  buf[0]=0;\n"
"  for(int i=off;i<end;i++){ if(i>off) strncat(buf,\" \",8192-strlen(buf)-1); strncat(buf,arr[i]?arr[i]:\"\",8192-strlen(buf)-1); }\n"
"  return buf;\n"
"}\n"
"static const char *__sh_substr(const char *s,int off,int len){\n"
"  char *buf = __sh_pool_next(__sh_substr_p0,__sh_substr_p1,__sh_substr_p2,__sh_substr_p3,&__sh_substr_i);\n"
"  int n=(int)strlen(s);\n"
"  if(off<0){ off+=n; if(off<0) return \"\"; /* negative offset beyond string → empty */ }\n"
"  if(off>n) return \"\";  /* out-of-bounds → empty string */\n"
"  int end = (len<0)? n : off+len; if(end>n) end=n;\n"
"  int l=end-off; if(l<0) l=0; if(l>=4096) l=4095;\n"
"  memcpy(buf,s+off,l); buf[l]=0;\n"
"  return buf;\n"
"}\n"
"static const char *__sh_strip_prefix(const char *s,const char *pat,int greedy){\n"
"  char *buf = __sh_pool_next(__sh_strip_p0,__sh_strip_p1,__sh_strip_p2,__sh_strip_p3,&__sh_strip_i);\n"
"  int best=0; int n=(int)strlen(s);\n"
"  if(greedy){ for(int i=n;i>=1;i--){ char tmp[1024]; int l=i; if(l>=(int)sizeof(tmp)) continue; memcpy(tmp,s,l); tmp[l]=0; if(fnmatch(pat,tmp,0)==0){ best=i; break; } } }\n"
"  else { for(int i=1;i<=n;i++){ char tmp[1024]; int l=i; if(l>=(int)sizeof(tmp)) continue; memcpy(tmp,s,l); tmp[l]=0; if(fnmatch(pat,tmp,0)==0){ best=i; break; } } }\n"
"  snprintf(buf,4096,\"%s\",s+best);\n"
"  return buf;\n"
"}\n"
"static const char *__sh_strip_suffix(const char *s,const char *pat,int greedy){\n"
"  char *buf = __sh_pool_next(__sh_strip_p0,__sh_strip_p1,__sh_strip_p2,__sh_strip_p3,&__sh_strip_i);\n"
"  int n=(int)strlen(s); int best=n;\n"
"  if(!greedy){ for(int i=n;i>=1;i--){ if(fnmatch(pat,s+i,0)==0){ best=i; break; } } }\n"
"  else { for(int i=1;i<=n;i++){ if(fnmatch(pat,s+i,0)==0){ best=i; break; } } }\n"
"  int l=best; if(l<0) l=0; if(l>=4096) l=4095;\n"
"  memcpy(buf,s,l); buf[l]=0;\n"
"  return buf;\n"
"}\n"
"static const char *__sh_replace(const char *s,const char *old,const char *newp,int global,int anchor_start,int anchor_end){\n"
"  char *out = __sh_pool_next(__sh_replace_p0,__sh_replace_p1,__sh_replace_p2,__sh_replace_p3,&__sh_replace_i);\n"
"  int oi=0; int sl=(int)strlen(s); int ol=(int)strlen(old); int nl=(int)strlen(newp);\n"
"  int i=0; int done=0;\n"
"  while(i<sl && oi<4096-nl-2){\n"
"    if(!done && (anchor_start?i==0:1) && (anchor_end?(i+ol==sl):1) && strncmp(s+i,old,ol)==0){\n"
"      memcpy(out+oi,newp,nl); oi+=nl; i+=ol; if(!global){ done=1; }\n"
"      if(anchor_start) anchor_start=0;\n"
"      if(anchor_end) anchor_end=0;\n"
"    } else { out[oi++]=s[i++]; }\n"
"  }\n"
"  out[oi]=0;\n"
"  return out;\n"
"}\n"
"static const char *__sh_upper(const char *s){\n"
"  char *buf = __sh_pool_next(__sh_upper_p0,__sh_upper_p1,__sh_upper_p2,__sh_upper_p3,&__sh_upper_i);\n"
"  int i; for(i=0;s[i]&&i<4095;i++) buf[i]=toupper((unsigned char)s[i]); buf[i]=0; return buf;\n"
"}\n"
"static const char *__sh_lower(const char *s){\n"
"  char *buf = __sh_pool_next(__sh_lower_p0,__sh_lower_p1,__sh_lower_p2,__sh_lower_p3,&__sh_lower_i);\n"
"  int i; for(i=0;s[i]&&i<4095;i++) buf[i]=tolower((unsigned char)s[i]); buf[i]=0; return buf;\n"
"}\n"
"static const char *__sh_upper_first(const char *s){\n"
"  char *buf = __sh_pool_next(__sh_upper_p0,__sh_upper_p1,__sh_upper_p2,__sh_upper_p3,&__sh_upper_i);\n"
"  int i; for(i=0;s[i]&&i<4095;i++) buf[i]=(i==0)?toupper((unsigned char)s[i]):s[i]; buf[i]=0; return buf;\n"
"}\n"
"static const char *__sh_lower_first(const char *s){\n"
"  char *buf = __sh_pool_next(__sh_lower_p0,__sh_lower_p1,__sh_lower_p2,__sh_lower_p3,&__sh_lower_i);\n"
"  int i; for(i=0;s[i]&&i<4095;i++) buf[i]=(i==0)?tolower((unsigned char)s[i]):s[i]; buf[i]=0; return buf;\n"
"}\n"
"/* ${arr[@]#pattern} — strip prefix from each element, then join */\n"
"static const char *__sh_strip_prefix(const char *s,const char *pat,int greedy);\n"
"static const char *__sh_strip_suffix(const char *s,const char *pat,int greedy);\n"
"static const char *__sh_arr_strip_prefix_all(const char **arr,const char *pat,int greedy){\n"
"  char *buf = __sh_pool_next(__sh_arr_p0,__sh_arr_p1,__sh_arr_p2,__sh_arr_p3,&__sh_arr_i);\n"
"  buf[0]=0;\n"
"  for(int i=0;arr[i]&&i<256;i++){ const char *r=__sh_strip_prefix(arr[i],pat,greedy); if(i>0) strncat(buf,\" \",8192-strlen(buf)-1); strncat(buf,r,8192-strlen(buf)-1); }\n"
"  return buf;\n"
"}\n"
"/* ${arr[@]%%pattern} — strip suffix from each element, then join */\n"
"static const char *__sh_arr_strip_suffix_all(const char **arr,const char *pat,int greedy){\n"
"  char *buf = __sh_pool_next(__sh_arr_p0,__sh_arr_p1,__sh_arr_p2,__sh_arr_p3,&__sh_arr_i);\n"
"  buf[0]=0;\n"
"  for(int i=0;arr[i]&&i<256;i++){ const char *r=__sh_strip_suffix(arr[i],pat,greedy); if(i>0) strncat(buf,\" \",8192-strlen(buf)-1); strncat(buf,r,8192-strlen(buf)-1); }\n"
"  return buf;\n"
"}\n"
"/* ${arr[@]^^}/${arr[@],,} — upper/lower each element, then join */\n"
"static const char *__sh_upper(const char *s);\n"
"static const char *__sh_lower(const char *s);\n"
"static const char *__sh_upper_first(const char *s);\n"
"static const char *__sh_lower_first(const char *s);\n"
"static const char *__sh_arr_case_all(const char **arr,int mode){\n"
"  char *buf = __sh_pool_next(__sh_arr_p0,__sh_arr_p1,__sh_arr_p2,__sh_arr_p3,&__sh_arr_i);\n"
"  buf[0]=0;\n"
"  for(int i=0;arr[i]&&i<256;i++){ const char *r;\n"
"    if(mode==2) r=__sh_upper(arr[i]);\n"
"    else if(mode==1) r=__sh_upper_first(arr[i]);\n"
"    else if(mode==-2) r=__sh_lower(arr[i]);\n"
"    else r=__sh_lower_first(arr[i]);\n"
"    if(i>0) strncat(buf,\" \",8192-strlen(buf)-1); strncat(buf,r,8192-strlen(buf)-1); }\n"
"  return buf;\n"
"}\n"
"/* ${arr[@]/old/new} — replace in each element, then join */\n"
"static const char *__sh_arr_replace_all(const char **arr,const char *old,const char *newp,int global){\n"
"  char *buf = __sh_pool_next(__sh_arr_p0,__sh_arr_p1,__sh_arr_p2,__sh_arr_p3,&__sh_arr_i);\n"
"  buf[0]=0;\n"
"  for(int i=0;arr[i]&&i<256;i++){ const char *r=__sh_replace(arr[i],old,newp,global,0,0); if(i>0) strncat(buf,\" \",8192-strlen(buf)-1); strncat(buf,r,8192-strlen(buf)-1); }\n"
"  return buf;\n"
"}\n"
"static const char *__sh_cmd_output(const char *cmd){\n"
"  char *buf = __sh_pool_next(__sh_cmd_out_p0,__sh_cmd_out_p1,__sh_cmd_out_p2,__sh_cmd_out_p3,&__sh_cmd_out_i);\n"
"  /* Expand braces {1..5}→1 2 3 4 5, {a,b}→a b before execution */\n"
"  char expcmd[65536];\n"
"  if(strchr(cmd,'{')){\n"
"    const char *s=cmd; int di=0;\n"
"    while(*s&&di<(int)sizeof(expcmd)-4){\n"
"      if(*s=='{'){\n"
"        const char *end=strchr(s,'}');\n"
"        if(end&&end-s>2){\n"
"          char inner[256]; int il=end-s-1;\n"
"          if(il<256){\n"
"            memcpy(inner,s+1,il); inner[il]=0;\n"
"            char *dot=strstr(inner,\"..\");\n"
"            if(dot){ *dot=0; char *st=inner, *en=dot+2;\n"
"              if(isdigit((unsigned char)st[0])&&isdigit((unsigned char)en[0])){\n"
"                int a=atoi(st),b=atoi(en);\n"
"                if(a<=b&&b-a<100000){ for(int n=a;n<=b&&di<(int)sizeof(expcmd)-4;n++){ if(n>a)expcmd[di++]=' '; di+=snprintf(expcmd+di,sizeof(expcmd)-di,\"%d\",n);} s=end+1; continue; }\n"
"              } else if(isalpha((unsigned char)st[0])&&isalpha((unsigned char)en[0])&&st[1]==0&&en[1]==0){\n"
"                char a=st[0],b=en[0];\n"
"                if(a<=b){ for(char c=a;c<=b&&di<(int)sizeof(expcmd)-4;c++){ if(c>a)expcmd[di++]=' '; expcmd[di++]=c;} s=end+1; continue; }\n"
"              }\n"
"            } else { char *tk=strtok(inner,\",\"); while(tk){ if(di>0&&expcmd[di-1]!=' ')expcmd[di++]=' '; int tl=strlen(tk); if(di+tl<(int)sizeof(expcmd)-2){memcpy(expcmd+di,tk,tl);di+=tl;} tk=strtok(NULL,\",\"); } s=end+1; continue; }\n"
"          }\n"
"        }\n"
"      }\n"
"      expcmd[di++]=*s++;\n"
"    }\n"
"    expcmd[di]=0; cmd=expcmd;\n"
"  }\n"
"  /* Capture stderr via fd duplication (no command modification) */\n"
"  char __ef[]=\"/tmp/.s2c_e_XXXXXX\"; int __efd=mkstemp(__ef);\n"
"  int __esaved=-1;\n"
"  if(__efd>=0){ close(__efd); __esaved=dup(2); int __enew=open(__ef,O_WRONLY|O_TRUNC,0600); if(__enew>=0){ dup2(__enew,2); close(__enew); } }\n"
"  FILE *p=popen(cmd,\"r\"); if(!p){ if(__esaved>=0){dup2(__esaved,2);close(__esaved);} if(__efd>=0) unlink(__ef); buf[0]=0; return buf; }\n"
"  size_t n=fread(buf,1,65535,p); pclose(p);\n"
"  if(__esaved>=0){ dup2(__esaved,2); close(__esaved); }\n"
"  if(n>0 && buf[n-1]=='\\n') n--;\n"
"  buf[n]=0;\n"
"  if(__efd>=0){\n"
"    FILE *ef=fopen(__ef,\"r\"); if(ef){\n"
"      char eb[4096]; size_t el=fread(eb,1,4095,ef); fclose(ef); eb[el]=0; unlink(__ef);\n"
"      if(el>0){\n"
"        char *nf=strstr(eb,\"not found\");\n"
"        if(nf){\n"
"          char *c1=strchr(eb,':'); char *c2=c1?strchr(c1+1,':'):NULL; char *c3=c2?strchr(c2+1,':'):NULL;\n"
"          if(c3){ char *cs=c2+1; while(*cs==' ')cs++; int cl=c3-cs; while(cl>0&&cs[cl-1]==' ')cl--;\n"
"            if(cl>0) fprintf(stderr,\"%s: line %d: %.*s: command not found\\n\",__sh_script_name[0]?__sh_script_name:\"shell2c\",__sh_lineno,cl,cs);\n"
"            else fputs(eb,stderr);\n"
"          } else fputs(eb,stderr);\n"
"        } else fputs(eb,stderr);\n"
"      }\n"
"    }\n"
"  }\n"
"  return buf;\n"
"}\n"
"static void __sh_usleep(unsigned us){ usleep(us); }\n"
"/* [[ ]] extended test — returns \"1\" if true, \"\" if false */\n"
"static const char *__sh_test_ext(const char *cond){\n"
"  /* Simple [[ ]] parser: supports -n VAR, -z VAR, VAR -ge N, VAR -le N, VAR -gt N, VAR -lt N, VAR == STR, VAR != STR */\n"
"  static char result[32];\n"
"  char lhs[256]; char op[16]; char rhs[256];\n"
"  lhs[0]=op[0]=rhs[0]=0;\n"
"  /* Parse: tokenize by spaces */\n"
"  int n=sscanf(cond,\"%255s %15s %255s\",lhs,op,rhs);\n"
"  int truth=0;\n"
"  if(n>=2){\n"
"    if(!strcmp(op,\"-n\")) truth = (lhs[0]!=0);\n"
"    else if(!strcmp(op,\"-z\")) truth = (lhs[0]==0);\n"
"    else if(!strcmp(op,\"-ge\")&&n>=3) truth = (atoi(lhs)>=atoi(rhs));\n"
"    else if(!strcmp(op,\"-le\")&&n>=3) truth = (atoi(lhs)<=atoi(rhs));\n"
"    else if(!strcmp(op,\"-gt\")&&n>=3) truth = (atoi(lhs)>atoi(rhs));\n"
"    else if(!strcmp(op,\"-lt\")&&n>=3) truth = (atoi(lhs)<atoi(rhs));\n"
"    else if(!strcmp(op,\"-eq\")&&n>=3) truth = (atoi(lhs)==atoi(rhs));\n"
"    else if(!strcmp(op,\"-ne\")&&n>=3) truth = (atoi(lhs)!=atoi(rhs));\n"
"    else if(!strcmp(op,\"==\")&&n>=3) truth = (strcmp(lhs,rhs)==0);\n"
"    else if(!strcmp(op,\"!=\")&&n>=3) truth = (strcmp(lhs,rhs)!=0);\n"
"  } else if(n==1){\n"
"    /* [[ VAR ]] — true if non-empty */\n"
"    truth = (lhs[0]!=0);\n"
"  }\n"
"  strcpy(result, \"\"); /* [[ ]] doesn't produce stdout output in bash */\n"
"  return result;\n"
"}\n"
"static const char *__sh_fmt(const char *fmt, ...){\n"
"  char *buf = __sh_pool_next(__sh_fmt_p0,__sh_fmt_p1,__sh_fmt_p2,__sh_fmt_p3,&__sh_fmt_i);\n"
"  va_list ap; va_start(ap, fmt);\n"
"  vsnprintf(buf, 8192, fmt, ap);\n"
"  va_end(ap); return buf;\n"
"}\n"
"/* Dynamic-growth formatting pool: like __sh_fmt but never truncates.\n"
" * 8 rotating slots, each grows on demand via realloc. Returned pointers\n"
" * stay valid until the same slot is reused 8 calls later; results are\n"
" * meant to be consumed within the current statement (as printf args,\n"
" * strdup sources, etc.). NULL/alloc-failure safe (returns \"\"). */\n"
"static char *__sh_dyn_p[8]={NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL};\n"
"static size_t __sh_dyn_cap[8]={0,0,0,0,0,0,0,0};\n"
"static int __sh_dyn_i=0;\n"
"static const char *__sh_fmt_dyn(const char *fmt, ...){\n"
"  va_list ap; va_start(ap,fmt);\n"
"  int need=vsnprintf(NULL,0,fmt,ap); va_end(ap);\n"
"  if(need<0) return \"\";\n"
"  int slot=__sh_dyn_i; __sh_dyn_i=(__sh_dyn_i+1)&7;\n"
"  if(__sh_dyn_cap[slot] < (size_t)need+1){\n"
"    size_t nc=__sh_dyn_cap[slot]?__sh_dyn_cap[slot]*2:1024;\n"
"    while(nc < (size_t)need+1) nc*=2;\n"
"    char *nb=realloc(__sh_dyn_p[slot],nc);\n"
"    if(!nb) return \"\";\n"
"    __sh_dyn_p[slot]=nb; __sh_dyn_cap[slot]=nc;\n"
"  }\n"
"  va_start(ap,fmt);\n"
"  vsnprintf(__sh_dyn_p[slot],__sh_dyn_cap[slot],fmt,ap);\n"
"  va_end(ap);\n"
"  return __sh_dyn_p[slot];\n"
"}\n"
"static const char *__sh_capture_fn(void (*fn)(int,char**), int argc, char **argv){\n"
"  char *buf = __sh_pool_next(__sh_fn_out_p0,__sh_fn_out_p1,__sh_fn_out_p2,__sh_fn_out_p3,&__sh_fn_out_i);\n"
"  int pfd[2]; if(pipe(pfd)<0){ buf[0]=0; return buf; }\n"
"  pid_t pid=fork();\n"
"  if(pid==0){\n"
"    close(pfd[0]); dup2(pfd[1],1); close(pfd[1]);\n"
"    setvbuf(stdout,NULL,_IONBF,0);\n"
"    fn(argc,argv);\n"
"    fflush(stdout); _exit(0);\n"
"  }\n"
"  close(pfd[1]);\n"
"  size_t n=0; while(n<65535){ ssize_t r=read(pfd[0],buf+n,65535-n); if(r<=0)break; n+=r; }\n"
"  close(pfd[0]);\n"
"  waitpid(pid,NULL,0);\n"
"  if(n>0 && buf[n-1]=='\\n') n--;\n"
"  buf[n]=0;\n"
"  return buf;\n"
"}\n"
"/* Process substitution: <(cmd) or >(cmd).\n"
" * Returns a /dev/fd/N path string. For <(cmd), cmd's stdout is connected\n"
" * to the read end. For >(cmd), cmd's stdin is connected to the write end. */\n"
"static const char *__sh_proc_subst(const char *cmd, char dir){\n"
"  char *buf = __sh_pool_next(__sh_ps_p0,__sh_ps_p1,__sh_ps_p2,__sh_ps_p3,&__sh_ps_i);\n"
"  int pfd[2]; if(pipe(pfd)<0){ snprintf(buf,64,\"/dev/null\"); return buf; }\n"
"  pid_t pid=fork();\n"
"  if(pid==0){\n"
"    if(dir=='<'){ close(pfd[0]); dup2(pfd[1],1); close(pfd[1]); }\n"
"    else { close(pfd[1]); dup2(pfd[0],0); close(pfd[0]); }\n"
"    /* The fast execvp path is only safe when the command contains no shell\n"
"     * metacharacters and no quotes: strtok tokenization cannot handle\n"
"     * semicolons, pipes, quoted args with spaces, or substitutions.\n"
"     * e.g. <(echo \"a\"; echo \"b\") MUST run through sh -c. */\n"
"    int simple=1;\n"
"    for(const char *c=cmd;*c;c++){\n"
"      if(strchr(\";|&<>()\\\"'$`\\\\\",*c)){ simple=0; break; }\n"
"    }\n"
"    if(!simple){\n"
"      execl(\"/bin/sh\",\"sh\",\"-c\",cmd,(char*)NULL);\n"
"      _exit(127);\n"
"    }\n"
"    char pcopy[4096]; strncpy(pcopy,cmd,sizeof(pcopy)-1); pcopy[sizeof(pcopy)-1]=0;\n"
"    char *av[128]; int ai=0; char *tk=strtok(pcopy,\" \\t\");\n"
"    while(tk&&ai<127){ av[ai++]=tk; tk=strtok(NULL,\" \\t\"); }\n"
"    av[ai]=NULL;\n"
"    if(ai>0) execvp(av[0],av);\n"
"    _exit(127);\n"
"  }\n"
"  if(dir=='<'){ close(pfd[1]); snprintf(buf,64,\"/dev/fd/%d\",pfd[0]); }\n"
"  else { close(pfd[0]); snprintf(buf,64,\"/dev/fd/%d\",pfd[1]); }\n"
"  return buf;\n"
"}\n"
"static void __sh_echo_escape(const char *s){\n"
"  while(*s){ if(*s=='\\\\' && *(s+1)){ s++; switch(*s){ case 'n':putchar('\\n');break; case 't':putchar('\\t');break; case 'r':putchar('\\r');break; case '\\\\':putchar('\\\\');break; case '0':putchar('\\0');break; default:putchar(*s);break; } s++; } else putchar(*s++); }\n"
"}\n"
"static void __sh_printf(const char *fmt,...){\n"
"  /* Shell-style printf: all args are strings, %d/%i convert via atoi */\n"
"  /* Supports format modifiers: %05d, %-10s, %.2f, etc. */\n"
"  va_list ap; va_start(ap,fmt);\n"
"  const char *p=fmt;\n"
"  while(*p){\n"
"    if(*p=='%' && *(p+1)){\n"
"      p++;\n"
"      /* collect format modifiers: flags, width, .precision */\n"
"      char mods[32]; int mi=0;\n"
"      while(*p && (*p=='-'||*p=='+'||*p==' '||*p=='#'||*p=='0'||\n"
"             (*p>='1'&&*p<='9')||*p=='.'||*p=='*') && mi<30){\n"
"        mods[mi++]=*p++;\n"
"      }\n"
"      mods[mi]=0;\n"
"      if(*p=='d'||*p=='i'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%sd\",mods); printf(f,s?atoi(s):0); }\n"
"      else if(*p=='s'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%ss\",mods); printf(f,s?s:\"\"); }\n"
"      else if(*p=='c'){ const char *s=va_arg(ap,const char*); putchar(s?s[0]:' '); }\n"
"      else if(*p=='x'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%sx\",mods); printf(f,s?atoi(s):0); }\n"
"      else if(*p=='X'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%sX\",mods); printf(f,s?atoi(s):0); }\n"
"      else if(*p=='o'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%so\",mods); printf(f,s?atoi(s):0); }\n"
"      else if(*p=='f'||*p=='e'||*p=='g'||*p=='E'||*p=='G'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%sf\",mods); printf(f,s?atof(s):0.0); }\n"
"      else if(*p=='%'){ putchar('%'); }\n"
"      else if(*p=='b'){ const char *s=va_arg(ap,const char*); /* %b: interpret backslash escapes */ __sh_echo_escape(s?s:\"\"); }\n"
"      else if(*p=='q'){ const char *s=va_arg(ap,const char*); /* %q: shell-escape — single-quote */ putchar('\\''); if(s){while(*s){if(*s=='\\'')fputs(\"'\\\\''\",stdout);else putchar(*s);s++;}}putchar('\\''); }\n"
"      else { putchar('%'); fputs(mods,stdout); putchar(*p); }\n"
"    } else { putchar(*p); }\n"
"    p++;\n"
"  }\n"
"  va_end(ap); fflush(stdout);\n"
"}\n"
"/* BUG-16 fix: printf -v variant — write to buffer instead of stdout */\n"
"static void __sh_sprintf(char *buf, int bufsz, const char *fmt,...){\n"
"  va_list ap; va_start(ap,fmt);\n"
"  int bi=0;\n"
"  const char *p=fmt;\n"
"  while(*p && bi<bufsz-1){\n"
"    if(*p=='%' && *(p+1)){\n"
"      p++;\n"
"      char mods[32]; int mi=0;\n"
"      while(*p && (*p=='-'||*p=='+'||*p==' '||*p=='#'||*p=='0'||\n"
"             (*p>='1'&&*p<='9')||*p=='.'||*p=='*') && mi<30){\n"
"        mods[mi++]=*p++;\n"
"      }\n"
"      mods[mi]=0;\n"
"      if(*p=='d'||*p=='i'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%sd\",mods); bi+=snprintf(buf+bi,bufsz-bi,f,s?atoi(s):0); }\n"
"      else if(*p=='s'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%ss\",mods); bi+=snprintf(buf+bi,bufsz-bi,f,s?s:\"\"); }\n"
"      else if(*p=='c'){ const char *s=va_arg(ap,const char*); buf[bi++]=s?s[0]:' '; }\n"
"      else if(*p=='x'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%sx\",mods); bi+=snprintf(buf+bi,bufsz-bi,f,s?atoi(s):0); }\n"
"      else if(*p=='X'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%sX\",mods); bi+=snprintf(buf+bi,bufsz-bi,f,s?atoi(s):0); }\n"
"      else if(*p=='o'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%so\",mods); bi+=snprintf(buf+bi,bufsz-bi,f,s?atoi(s):0); }\n"
"      else if(*p=='f'||*p=='e'||*p=='g'){ const char *s=va_arg(ap,const char*); char f[40]; snprintf(f,sizeof(f),\"%%%sf\",mods); bi+=snprintf(buf+bi,bufsz-bi,f,s?atof(s):0.0); }\n"
"      else if(*p=='%'){ buf[bi++]='%'; }\n"
"      else { buf[bi++]='%'; for(int j=0;j<mi;j++) buf[bi++]=mods[j]; buf[bi++]=*p; }\n"
"    } else { buf[bi++]=*p; }\n"
"    p++;\n"
"  }\n"
"  buf[bi]=0; va_end(ap);\n"
"}\n"
"/* Elegant output helpers — reduce repetitive fputs+putchar patterns */\n"
"static void __sh_puts(const char *s){ if(__sh_div_error){__sh_div_error=0;return;} "
"/* Use write() directly to avoid glibc stdio buffer leaking plaintext */ "
"size_t _sl=strlen(s); write(1,s,_sl); write(1,\"\\n\",1); }\n"
"static void __sh_putf(const char *fmt,...){\n"
"  if(__sh_div_error){__sh_div_error=0;return;}\n"
"  va_list ap; va_start(ap,fmt); char _buf[4096]; int _n=vsnprintf(_buf,sizeof(_buf),fmt,ap); va_end(ap);\n"
"  if(_n>0) write(1,_buf,_n); write(1,\"\\n\",1);\n"
"  memset(_buf,0,sizeof(_buf));\n"
"}\n"
"static void __sh_arr_free(char **arr){ for(int i=0;arr[i];i++) free(arr[i]); free(arr); }\n"
"/* ---- test(1) helpers ---- */\n"
"static int __sh_test_file(const char *p,int dir){ struct stat st; if(stat(p,&st)!=0) return 0; return dir?S_ISDIR(st.st_mode):1; }\n"
"static int __sh_test_sfile(const char *p){ struct stat st; if(stat(p,&st)!=0) return 0; return st.st_size>0; }\n"
"static int __sh_test_link(const char *p){ struct stat st; if(lstat(p,&st)!=0) return 0; return S_ISLNK(st.st_mode); }\n"
"static int __sh_test_fifo(const char *p){ struct stat st; if(stat(p,&st)!=0) return 0; return S_ISFIFO(st.st_mode); }\n"
"static int __sh_test_sock(const char *p){ struct stat st; if(stat(p,&st)!=0) return 0; return S_ISSOCK(st.st_mode); }\n"
"static int __sh_test_blk(const char *p){ struct stat st; if(stat(p,&st)!=0) return 0; return S_ISBLK(st.st_mode); }\n"
"static int __sh_test_chr(const char *p){ struct stat st; if(stat(p,&st)!=0) return 0; return S_ISCHR(st.st_mode); }\n"
"static int __sh_test_mode(const char *p,int mask){ struct stat st; if(stat(p,&st)!=0) return 0; return (st.st_mode&mask)!=0; }\n"
"static int __sh_test_var(const char *name){ return getenv(name)!=NULL; }\n"
"static int __sh_test_owner(const char *p){ struct stat st; if(stat(p,&st)!=0) return 0; return st.st_uid==getuid(); }\n"
"static int __sh_test_group(const char *p){ struct stat st; if(stat(p,&st)!=0) return 0; return st.st_gid==getgid(); }\n"
"static int __sh_test_newer(const char *p){ struct stat st; if(stat(p,&st)!=0) return 0; return st.st_mtime>st.st_atime; }\n"
"static int __sh_test_same(const char *a,const char *b){ struct stat sa,sb; if(stat(a,&sa)!=0||stat(b,&sb)!=0) return 0; return sa.st_dev==sb.st_dev&&sa.st_ino==sb.st_ino; }\n"
"static int __sh_test_nt(const char *a,const char *b){ struct stat sa,sb; if(stat(a,&sa)!=0) return 0; if(stat(b,&sb)!=0) return 1; return sa.st_mtime>sb.st_mtime; }\n"
"static int __sh_test_ot(const char *a,const char *b){ struct stat sa,sb; if(stat(a,&sa)!=0) return 0; if(stat(b,&sb)!=0) return 0; return sa.st_mtime<sb.st_mtime; }\n"
"static int __sh_test_cmd(const char *cmd){ FILE *p=popen(cmd,\"r\"); if(!p) return 0; char buf[1024]; int got=0; while(fgets(buf,sizeof(buf),p)){ got=1; } pclose(p); return got; }\n"
"/* Exit-status semantics for if <command> conditions (POSIX). */\n"
"static int __sh_cmd_status(const char *cmd){ int st=system(cmd); if(st==-1) return 127; if(WIFEXITED(st)) return WEXITSTATUS(st); return 1; }\n"
"static int __sh_regex(const char *s,const char *pat){ regex_t r; if(regcomp(&r,pat,REG_EXTENDED|REG_NOSUB)!=0) return 0; int rc=regexec(&r,s,0,NULL,0); regfree(&r); return rc==0; }\n"
"\n"
"/* ---- file builtins ---- */\n"
"static void __attribute__((unused)) __b_pwd(void){ char b[4096]; if(getcwd(b,sizeof(b)))printf(\"%s\\n\",b); else perror(\"pwd\"); }\n"
"static void __attribute__((unused)) __b_ls(const char *flags,...){\n"
"  va_list ap; va_start(ap,flags);\n"
"  int show_all=0,long_fmt=0,rev=0;\n"
"  for(const char *f=flags;f&&*f;f++){ if(*f=='a')show_all=1; if(*f=='l')long_fmt=1; if(*f=='r')rev=1; }\n"
"  const char *path; int first=1; int had_arg=0;\n"
"  while((path=va_arg(ap,const char*))!=NULL){\n"
"    had_arg=1;\n"
"    DIR *dp=opendir(path[0]?path:\".\"); if(!dp){char __lbuf[512]; int __lbn=snprintf(__lbuf,sizeof(__lbuf),\"ls: cannot access '%s': %s\\n\",path,strerror(errno)); write(2,__lbuf,__lbn); __exit_status=2;continue;}\n"
"    if(!first) printf(\"\\n\");\n    first=0;\n"
"    struct dirent *e; struct stat st; char full[4096];\n"
"    while((e=readdir(dp))){ if(!show_all&&e->d_name[0]=='.') continue;\n"
"      if(long_fmt){ snprintf(full,sizeof(full),\"%s/%s\",path,e->d_name); if(stat(full,&st)==0){ printf(\"%c %8ld %s\\n\",S_ISDIR(st.st_mode)?'d':'-',(long)st.st_size,e->d_name); } else printf(\"? %8s %s\\n\",\"?\",e->d_name); }\n"
"      else printf(\"%s\\n\",e->d_name);\n"
"    }\n"
"    closedir(dp);\n"
"  }\n"
"  if(!had_arg){ DIR *dp=opendir(\".\"); if(dp){ struct dirent *e; while((e=readdir(dp)))if(show_all||e->d_name[0]!='.')printf(\"%s\\n\",e->d_name); closedir(dp);} }\n"
"  va_end(ap);\n"
"}\n"
"static int __attribute__((unused)) __b_cp(const char *s,const char *d){\n"
"  struct stat st; if(stat(s,&st)==0 && S_ISDIR(st.st_mode)){ char cmd[8192]; snprintf(cmd,sizeof(cmd),\"cp -r \\\"%s\\\" \\\"%s\\\"\",s,d); return system(cmd); }\n"
"  int f1=open(s,O_RDONLY); if(f1<0){perror(\"cp\");return-1;}\n"
"  int f2=open(d,O_WRONLY|O_CREAT|O_TRUNC,0644); if(f2<0){perror(\"cp\");close(f1);return-1;}\n"
"  char buf[65536]; ssize_t r;\n"
"  while((r=read(f1,buf,sizeof(buf)))>0){ ssize_t w=0;while(w<r){ssize_t x=write(f2,buf+w,r-w);if(x<0){perror(\"cp\");close(f1);close(f2);return-1;}w+=x;}}\n"
"  close(f1);close(f2);return 0;\n"
"}\n"
"static int __attribute__((unused)) __b_mv(const char *s,const char *d){if(rename(s,d)!=0){perror(\"mv\");return-1;}return 0;}\n"
"static int __attribute__((unused)) __b_rm(const char *p,int recursive){\n"
"  struct stat st; if(stat(p,&st)!=0){perror(\"rm\");return-1;}\n"
"  if(S_ISDIR(st.st_mode)){ if(recursive){ char cmd[8192]; snprintf(cmd,sizeof(cmd),\"rm -rf \\\"%s\\\"\",p); return system(cmd); } else { if(rmdir(p)!=0){perror(\"rm\");return-1;} } }\n"
"  else { if(unlink(p)!=0){perror(\"rm\");return-1;} }\n"
"  return 0;\n"
"}\n"
"static int __attribute__((unused)) __b_mkdir(const char *p,int parents){\n"
"  if(parents){ char tmp[1024]; strncpy(tmp,p,sizeof(tmp)-1); tmp[sizeof(tmp)-1]=0; int l=(int)strlen(tmp);\n"
"    for(int i=1;i<l;i++){ if(tmp[i]=='/'){ tmp[i]=0; mkdir(tmp,0755); tmp[i]='/'; } }\n"
"    return mkdir(tmp,0755);\n"
"  }\n"
"  if(mkdir(p,0755)!=0){perror(\"mkdir\");return-1;} return 0;\n"
"}\n"
"static int __attribute__((unused)) __b_rmdir(const char *p){if(rmdir(p)!=0){perror(\"rmdir\");return-1;}return 0;}\n"
"static void __attribute__((unused)) __b_touch(const char *p){ int fd=open(p,O_WRONLY|O_CREAT,0644);if(fd>=0)close(fd);else perror(\"touch\");}\n"
"static int __attribute__((unused)) __b_ln(const char *a,const char *b,int sym){ if(sym){ if(symlink(a,b)!=0){perror(\"ln\");return-1;} } else { if(link(a,b)!=0){perror(\"ln\");return-1;} } return 0; }\n"
"static int __attribute__((unused)) __b_chmod(const char *mode,const char *p){ int m=(int)strtol(mode,NULL,8); if(chmod(p,m)!=0){perror(\"chmod\");return-1;} return 0; }\n"
"static int __attribute__((unused)) __b_chown(const char *owner,const char *p){ char cmd[1024]; snprintf(cmd,sizeof(cmd),\"chown %s \\\"%s\\\"\",owner,p); return system(cmd); }\n"
"static void __attribute__((unused)) __b_stat(const char *p){ struct stat st; if(stat(p,&st)!=0){perror(\"stat\");return;} printf(\"  File: %s\\n  Size: %ld\\n\",p,(long)st.st_size); printf(\"  Mode: %o\\n\",st.st_mode&0777); printf(\"  Uid: %d  Gid: %d\\n\",st.st_uid,st.st_gid); }\n"
"static void __attribute__((unused)) __b_du(const char *p){ char cmd[1024]; snprintf(cmd,sizeof(cmd),\"du -sh \\\"%s\\\" 2>/dev/null\",p); system(cmd); }\n"
"static void __attribute__((unused)) __b_df(void){ system(\"df -h\"); }\n"
"static void __attribute__((unused)) __b_file(const char *p){ char cmd[1024]; snprintf(cmd,sizeof(cmd),\"file \\\"%s\\\"\",p); system(cmd); }\n"
"static void __attribute__((unused)) __b_basename(const char *p){ const char *b=strrchr(p,'/'); printf(\"%s\\n\",b?b+1:p); }\n"
"static void __attribute__((unused)) __b_dirname(const char *p){ char tmp[1024]; strncpy(tmp,p,sizeof(tmp)-1); tmp[sizeof(tmp)-1]=0; char *sl=strrchr(tmp,'/'); if(sl){ *sl=0; printf(\"%s\\n\",tmp[0]?tmp:\"/\"); } else printf(\".\\n\"); }\n"
"static void __attribute__((unused)) __b_realpath(const char *p){ char *r=realpath(p,NULL); if(r){ printf(\"%s\\n\",r); free(r); } else perror(\"realpath\"); }\n"
"static void __attribute__((unused)) __b_readlink(const char *p){ char buf[4096]; ssize_t n=readlink(p,buf,sizeof(buf)-1); if(n<0) perror(\"readlink\"); else { buf[n]=0; printf(\"%s\\n\",buf); } }\n"
"static void __attribute__((unused)) __b_mktemp(void){ char t[]=\"/tmp/sh2cXXXXXX\"; int fd=mkstemp(t); if(fd>=0){ printf(\"%s\\n\",t); close(fd); } }\n"
"static int __attribute__((unused)) __b_install(const char *s,const char *d){ return __b_cp(s,d); }\n"
"\n"
"/* ---- text builtins ---- */\n"
"static void __attribute__((unused)) __b_cat(const char *path,int flags){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"cat\");return;}\n"
"  char ln[8192]; int n=1;\n"
"  while(fgets(ln,sizeof(ln),f)){ if(flags&1) printf(\"%6d  %s\",n,ln); else fputs(ln,stdout); if(flags&2){ int l=(int)strlen(ln); if(l>0&&ln[l-1]=='\\n') ln[l-1]='$'; } n++; }\n"
"  if(path)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_grep(const char *pat,const char *path,const char *flags){\n"
"  int ignore_case=(flags&&strchr(flags,'i'))?REG_ICASE:0;\n"
"  int invert=(flags&&strchr(flags,'v'))?1:0;\n"
"  int line_no=(flags&&strchr(flags,'n'))?1:0;\n"
"  int count_only=(flags&&strchr(flags,'c'))?1:0;\n"
"  int match_count=0;\n"
"  regex_t r; if(regcomp(&r,pat,REG_EXTENDED|ignore_case)!=0){ fprintf(stderr,\"grep: bad pattern\\n\"); return; }\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"grep\");regfree(&r);return;}\n"
"  char ln[8192]; int n=1;\n"
"  while(fgets(ln,sizeof(ln),f)){ int m=regexec(&r,ln,0,NULL,0)==0; if(m!=invert){ if(count_only) match_count++; else { if(line_no) printf(\"%d:\",n); fputs(ln,stdout); } } n++; }\n"
"  if(path)fclose(f);\n"
"  if(count_only) printf(\"%d\\n\",match_count);\n"
"  regfree(&r);\n"
"}\n"
"static void __attribute__((unused)) __b_sed(const char *script,const char *path){\n"
"  /* support s/old/new/[g] and s|old|new|[g] */\n"
"  if(script[0]!='s'){ if(path){ char cmd[8192]; snprintf(cmd,sizeof(cmd),\"sed '%s' \\\"%s\\\"\",script,path); system(cmd); } else { char cmd[8192]; snprintf(cmd,sizeof(cmd),\"sed '%s'\",script); system(cmd); } return; }\n"
"  char delim=script[1]; const char *p=script+2; char old[1024]; int oi=0;\n"
"  while(*p && *p!=delim && oi<(int)sizeof(old)-1) old[oi++]=*p++;\n"
"  old[oi]=0; if(*p) p++;\n"
"  char newp[1024]; int ni=0;\n"
"  while(*p && *p!=delim && ni<(int)sizeof(newp)-1) newp[ni++]=*p++;\n"
"  newp[ni]=0; if(*p) p++;\n"
"  int global=0; while(*p){ if(*p=='g') global=1; p++; }\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"sed\");return;}\n"
"  char ln[8192];\n"
"  while(fgets(ln,sizeof(ln),f)){ char out[16384]; int oi2=0; int i=0; int ol=(int)strlen(old); int nl=(int)strlen(newp); int sl=(int)strlen(ln); int done=0;\n"
"    while(i<sl && oi2<(int)sizeof(out)-nl-2){ if(!done && ol>0 && strncmp(ln+i,old,ol)==0){ memcpy(out+oi2,newp,nl); oi2+=nl; i+=ol; if(!global) done=1; } else out[oi2++]=ln[i++]; }\n"
"    while(i<sl && oi2<(int)sizeof(out)-1) out[oi2++]=ln[i++];\n"
"    out[oi2]=0; fputs(out,stdout);\n"
"  }\n"
"  if(path)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_tr(const char *s1,const char *s2){\n"
"  /* Expand ranges like a-z, A-Z, 0-9 in s1 and s2 */\n"
"  char exp1[256], exp2[256]; int e1=0, e2=0;\n"
"  for(int i=0;s1[i]&&e1<255;i++){ if(s1[i]=='-'&&i>0&&s1[i+1]&&e1>0){ char lo=exp1[e1-1], hi=s1[i+1]; for(char c=lo+1;c<=hi&&e1<255;c++) exp1[e1++]=c; i++; } else exp1[e1++]=s1[i]; }\n"
"  exp1[e1]=0;\n"
"  for(int i=0;s2[i]&&e2<255;i++){ if(s2[i]=='-'&&i>0&&s2[i+1]&&e2>0){ char lo=exp2[e2-1], hi=s2[i+1]; for(char c=lo+1;c<=hi&&e2<255;c++) exp2[e2++]=c; i++; } else exp2[e2++]=s2[i]; }\n"
"  exp2[e2]=0;\n"
"  /* Interpret escape sequences in exp1 and exp2 */\n"
"  char real1[256], real2[256]; int r1=0, r2=0;\n"
"  for(int i=0;exp1[i]&&r1<255;i++){ if(exp1[i]=='\\\\' && exp1[i+1]){ char n=exp1[i+1]; real1[r1++]=(n=='n')?'\\n':(n=='t')?'\\t':(n=='r')?'\\r':n; i++; } else real1[r1++]=exp1[i]; }\n"
"  real1[r1]=0;\n"
"  for(int i=0;exp2[i]&&r2<255;i++){ if(exp2[i]=='\\\\' && exp2[i+1]){ char n=exp2[i+1]; real2[r2++]=(n=='n')?'\\n':(n=='t')?'\\t':(n=='r')?'\\r':n; i++; } else real2[r2++]=exp2[i]; }\n"
"  real2[r2]=0;\n"
"  int c; int l2=r2;\n"
"  while((c=fgetc(stdin))!=EOF){\n"
"    const char *p=strchr(real1,c);\n"
"    if(p){ int idx=(int)(p-real1); putchar(idx<l2?real2[idx]:(l2>0?real2[l2-1]:c)); }\n"
"    else putchar(c);\n"
"  }\n"
"}\n"
"static void __attribute__((unused)) __b_tr_delete(const char *set){\n"
"  /* Expand ranges and escape sequences in set */\n"
"  char exp1[256]; int e1=0;\n"
"  for(int i=0;set[i]&&e1<255;i++){ if(set[i]=='-'&&i>0&&set[i+1]&&e1>0){ char lo=exp1[e1-1], hi=set[i+1]; for(char c=lo+1;c<=hi&&e1<255;c++) exp1[e1++]=c; i++; } else exp1[e1++]=set[i]; }\n"
"  exp1[e1]=0;\n"
"  char real1[256]; int r1=0;\n"
"  for(int i=0;exp1[i]&&r1<255;i++){ if(exp1[i]=='\\\\' && exp1[i+1]){ char n=exp1[i+1]; real1[r1++]=(n=='n')?'\\n':(n=='t')?'\\t':(n=='r')?'\\r':n; i++; } else real1[r1++]=exp1[i]; }\n"
"  real1[r1]=0;\n"
"  int c;\n"
"  while((c=fgetc(stdin))!=EOF){\n"
"    if(!strchr(real1,c)) putchar(c);\n"
"  }\n"
"}\n"
"static void __attribute__((unused)) __b_cut(const char *fields,char delim,const char *path){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"cut\");return;}\n"
"  char ln[8192];\n"
"  while(fgets(ln,sizeof(ln),f)){\n"
"    int l=(int)strlen(ln); if(l>0&&ln[l-1]=='\\n') ln[--l]=0;\n"
"    /* parse fields like 1,3 or 1-3 */\n"
"    char fc[256]; strncpy(fc,fields,sizeof(fc)-1); fc[sizeof(fc)-1]=0;\n"
"    char *tok=strtok(fc,\",\"); int first=1;\n"
"    while(tok){ int a,b; if(strchr(tok,'-')){ sscanf(tok,\"%d-%d\",&a,&b); } else { a=b=atoi(tok); }\n"
"      int col=1; char *p=ln; char *start=p;\n"
"      while(*p){ if(*p==delim){ if(col>=a&&col<=b){ if(!first)putchar(delim); int len=(int)(p-start); printf(\"%.*s\",len,start); first=0; } col++; start=p+1; } p++; }\n"
"      if(col>=a&&col<=b){ if(!first)putchar(delim); fputs(start,stdout); first=0; }\n"
"      tok=strtok(NULL,\",\");\n"
"    }\n"
"    putchar('\\n');\n"
"  }\n"
"  if(path)fclose(f);\n"
"}\n"
"static int __sort_cmp(const void *a,const void *b){ return strcmp(*(const char**)a,*(const char**)b); }\n"
"static int __sort_cmp_rev(const void *a,const void *b){ return strcmp(*(const char**)b,*(const char**)a); }\n"
"static int __sort_cmp_num(const void *a,const void *b){ double da=atof(*(const char**)a),db=atof(*(const char**)b); return (da>db)-(da<db); }\n"
"static void __attribute__((unused)) __b_sort(const char *path,int rev,int uniq,int num){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"sort\");return;}\n"
"  char **lines=NULL; int n=0,cap=0; char ln[8192];\n"
"  while(fgets(ln,sizeof(ln),f)){ if(n>=cap){ cap=cap?cap*2:64; lines=realloc(lines,cap*sizeof(char*)); } lines[n++]=strdup(ln); }\n"
"  if(path)fclose(f);\n"
"  if(num) qsort(lines,n,sizeof(char*),rev?__sort_cmp_rev:__sort_cmp_num);\n"
"  else qsort(lines,n,sizeof(char*),rev?__sort_cmp_rev:__sort_cmp);\n"
"  const char *prev=NULL;\n"
"  for(int i=0;i<n;i++){ if(uniq&&prev&&strcmp(prev,lines[i])==0){ free(lines[i]); continue; } fputs(lines[i],stdout); prev=lines[i]; }\n"
"  for(int i=0;i<n;i++) free(lines[i]);\n"
"  free(lines);\n"
"}\n"
"static void __attribute__((unused)) __b_uniq(const char *path,int count){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"uniq\");return;}\n"
"  char ln[8192]; char prev[8192]=\"\"; int cnt=0,first=1;\n"
"  while(fgets(ln,sizeof(ln),f)){ int l=(int)strlen(ln); if(l>0&&ln[l-1]=='\\n') ln[--l]=0;\n"
"    if(first||strcmp(prev,ln)!=0){ if(!first){ if(count) printf(\"%7d %s\\n\",cnt,prev); else printf(\"%s\\n\",prev); } strcpy(prev,ln); cnt=1; first=0; }\n"
"    else cnt++;\n"
"  }\n"
"  if(!first){ if(count) printf(\"%7d %s\\n\",cnt,prev); else printf(\"%s\\n\",prev); }\n"
"  if(path)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_wc(const char *path,int dl,int dw,int dc){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"wc\");return;}\n"
"  long li=0,wi=0,ci=0; int iw=0,c;\n"
"  while((c=fgetc(f))!=EOF){ci++;if(c=='\\n')li++;if(isspace(c))iw=0;else if(!iw){iw=1;wi++;}}\n"
"  if(path)fclose(f);\n"
"  {int __w1=1;\n"
"  if(dl)printf(\"%s%ld\",__w1?\"\":\" \",li),__w1=0;\n"
"  if(dw)printf(\"%s%ld\",__w1?\"\":\" \",wi),__w1=0;\n"
"  if(dc)printf(\"%s%ld\",__w1?\"\":\" \",ci),__w1=0;\n"
"  if(path)printf(\"%s%s\",__w1?\"\":\" \",path);\n"
"  putchar('\\n');\n"
"  }\n"
"}\n"
"static void __attribute__((unused)) __b_head(const char *path,int n){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"head\");return;}\n"
"  char ln[8192]; int c=0; while(c<n&&fgets(ln,sizeof(ln),f)){fputs(ln,stdout);c++;}\n"
"  if(path)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_tail(const char *path,int n){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"tail\");return;}\n"
"  char **buf=(char**)malloc(n*sizeof(char*)); int i; for(i=0;i<n;i++)buf[i]=NULL;\n"
"  char ln[8192]; int idx=0,tot=0;\n"
"  while(fgets(ln,sizeof(ln),f)){free(buf[idx%n]);buf[idx%n]=strdup(ln);idx++;tot++;}\n"
"  if(path)fclose(f);\n"
"  int st=(tot>n)?idx%n:0,cnt=(tot>n)?n:tot;\n"
"  for(i=0;i<cnt;i++){int j=(st+i)%n;if(buf[j])fputs(buf[j],stdout);}\n"
"  for(i=0;i<n;i++)free(buf[i]);\n"
"  free(buf);\n"
"}\n"
"static void __attribute__((unused)) __b_tee(int append,...){\n"
"  va_list ap; va_start(ap,append);\n"
"  FILE **fps=NULL; int nf=0;\n"
"  const char *p;\n"
"  while((p=va_arg(ap,const char*))!=NULL){ fps=realloc(fps,(nf+1)*sizeof(FILE*)); fps[nf]=fopen(p,append?\"a\":\"w\"); nf++; }\n"
"  va_end(ap);\n"
"  int c; while((c=fgetc(stdin))!=EOF){ putchar(c); for(int i=0;i<nf;i++) if(fps[i]) fputc(c,fps[i]); }\n"
"  for(int i=0;i<nf;i++) if(fps[i]) fclose(fps[i]);\n"
"  free(fps);\n"
"}\n"
"static void __attribute__((unused)) __b_xargs(const char *first,...){\n"
"  va_list ap; va_start(ap,first);\n"
"  const char *extra[32]; int ne=0; const char *p;\n"
"  while((p=va_arg(ap,const char*))!=NULL && ne<31) extra[ne++]=p;\n"
"  va_end(ap);\n"
"  /* Build the xargs command */\n"
"  char full[16384]; int fl=0;\n"
"  fl+=snprintf(full+fl,sizeof(full)-fl,\"xargs %s\",first);\n"
"  for(int i=0;i<ne;i++){ fl+=snprintf(full+fl,sizeof(full)-fl,\" %s\",extra[i]); }\n"
"  /* Pass stdin directly to xargs, reading all lines */\n"
"  char ln[8192]; char all_lines[65536]; int al=0;\n"
"  while(fgets(ln,sizeof(ln),stdin)){ int l=(int)strlen(ln); if(al+l<(int)sizeof(all_lines)-2){ memcpy(all_lines+al,ln,l); al+=l; } }\n"
"  all_lines[al]=0;\n"
"  /* Write to temp file and use as stdin */\n"
"  FILE *xf=tmpfile(); if(xf){ fputs(all_lines,xf); fflush(xf); int xfd=fileno(xf); lseek(xfd,0,SEEK_SET);\n"
"    int saved=dup(0); dup2(xfd,0);\n"
"    system(full);\n"
"    dup2(saved,0); close(saved); fclose(xf);\n"
"  } else system(full);\n"
"}\n"
"static void __attribute__((unused)) __b_rev(const char *path){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"rev\");return;}\n"
"  char ln[8192]; while(fgets(ln,sizeof(ln),f)){ int l=(int)strlen(ln); if(l>0&&ln[l-1]=='\\n') ln[--l]=0; for(int i=l-1;i>=0;i--) putchar(ln[i]); putchar('\\n'); }\n"
"  if(path)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_tac(const char *path){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"tac\");return;}\n"
"  char **lines=NULL; int n=0,cap=0; char ln[8192];\n"
"  while(fgets(ln,sizeof(ln),f)){ if(n>=cap){cap=cap?cap*2:64; lines=realloc(lines,cap*sizeof(char*));} lines[n++]=strdup(ln); }\n"
"  if(path)fclose(f);\n"
"  for(int i=n-1;i>=0;i--){ fputs(lines[i],stdout); free(lines[i]); }\n"
"  free(lines);\n"
"}\n"
"static void __attribute__((unused)) __b_nl(const char *path){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"nl\");return;}\n"
"  char ln[8192]; int n=1; while(fgets(ln,sizeof(ln),f)){ printf(\"%6d  %s\",n,ln); n++; }\n"
"  if(path)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_fold(const char *path,int w){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"fold\");return;}\n"
"  int c,col=0; while((c=fgetc(f))!=EOF){ putchar(c); if(c=='\\n') col=0; else { col++; if(col>=w){ putchar('\\n'); col=0; } } }\n"
"  if(path)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_paste(const char *first,...){\n"
"  va_list ap; va_start(ap,first);\n"
"  FILE *fps[16]; const char *names[16]; int nf=0;\n"
"  if(first){ names[nf]=first; fps[nf]=fopen(first,\"r\"); nf++; }\n"
"  const char *p; while((p=va_arg(ap,const char*))!=NULL && nf<16){ names[nf]=p; fps[nf]=fopen(p,\"r\"); nf++; }\n"
"  va_end(ap);\n"
"  if(nf==0) return;\n"
"  char lns[16][8192]; int alive=1;\n"
"  while(alive){ alive=0; for(int i=0;i<nf;i++){ if(fps[i]&&fgets(lns[i],sizeof(lns[i]),fps[i])){ alive=1; int l=(int)strlen(lns[i]); if(l>0&&lns[i][l-1]=='\\n') lns[i][--l]=0; } else lns[i][0]=0; if(i>0) putchar('\\t'); fputs(lns[i],stdout); } putchar('\\n'); }\n"
"  for(int i=0;i<nf;i++) if(fps[i]) fclose(fps[i]);\n"
"}\n"
"static void __attribute__((unused)) __b_expand(const char *path){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"expand\");return;}\n"
"  int c,col=0; while((c=fgetc(f))!=EOF){ if(c=='\\t'){ do{ putchar(' '); col++; }while(col%8); } else { putchar(c); if(c=='\\n') col=0; else col++; } }\n"
"  if(path)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_unexpand(const char *path){\n"
"  FILE *f=path?fopen(path,\"r\"):stdin; if(!f){perror(\"unexpand\");return;}\n"
"  int c,col=0,spaces=0; while((c=fgetc(f))!=EOF){ if(c==' '){ spaces++; col++; if(col%8==0){ putchar('\\t'); spaces=0; } } else { while(spaces>0){ putchar(' '); spaces--; } putchar(c); if(c=='\\n') col=0; else col++; } }\n"
"  if(path)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_column(const char *first,...){\n"
"  va_list ap; va_start(ap,first); const char *p; FILE *f=first?fopen(first,\"r\"):stdin; while((p=va_arg(ap,const char*))!=NULL){} va_end(ap);\n"
"  if(!f){perror(\"column\");return;}\n"
"  char ln[8192]; while(fgets(ln,sizeof(ln),f)){ fputs(ln,stdout); }\n"
"  if(first)fclose(f);\n"
"}\n"
"static void __attribute__((unused)) __b_shuf(const char *first,...){\n"
"  va_list ap; va_start(ap,first); const char *p; FILE *f=first?fopen(first,\"r\"):stdin; while((p=va_arg(ap,const char*))!=NULL){} va_end(ap);\n"
"  if(!f){perror(\"shuf\");return;}\n"
"  char **lines=NULL; int n=0,cap=0; char ln[8192];\n"
"  while(fgets(ln,sizeof(ln),f)){ if(n>=cap){cap=cap?cap*2:64; lines=realloc(lines,cap*sizeof(char*));} lines[n++]=strdup(ln); }\n"
"  if(first)fclose(f);\n"
"  srand((unsigned)time(NULL));\n"
"  for(int i=n-1;i>0;i--){ int j=rand()%(i+1); char *t=lines[i]; lines[i]=lines[j]; lines[j]=t; }\n"
"  for(int i=0;i<n;i++){ fputs(lines[i],stdout); free(lines[i]); } free(lines);\n"
"}\n"
"static void __attribute__((unused)) __b_comm(const char *a,const char *b){\n"
"  FILE *fa=fopen(a,\"r\"),*fb=fopen(b,\"r\"); if(!fa||!fb){perror(\"comm\");return;}\n"
"  char la[8192],lb[8192]; int ha=1,hb=1;\n"
"  ha=fgets(la,sizeof(la),fa)?1:0; hb=fgets(lb,sizeof(lb),fb)?1:0;\n"
"  while(ha||hb){\n"
"    if(ha&&hb){ int l=(int)strlen(la); if(l>0&&la[l-1]=='\\n')la[--l]=0; l=(int)strlen(lb); if(l>0&&lb[l-1]=='\\n')lb[--l]=0;\n"
"      int c=strcmp(la,lb); if(c<0){ printf(\"%s\\n\",la); ha=fgets(la,sizeof(la),fa)?1:0; } else if(c>0){ printf(\"\\t%s\\n\",lb); hb=fgets(lb,sizeof(lb),fb)?1:0; } else { printf(\"\\t\\t%s\\n\",la); ha=fgets(la,sizeof(la),fa)?1:0; hb=fgets(lb,sizeof(lb),fb)?1:0; } }\n"
"    else if(ha){ fputs(la,stdout); ha=fgets(la,sizeof(la),fa)?1:0; } else { printf(\"\\t%s\",lb); hb=fgets(lb,sizeof(lb),fb)?1:0; }\n"
"  }\n"
"  fclose(fa); fclose(fb);\n"
"}\n"
"static void __attribute__((unused)) __b_diff(const char *a,const char *b){\n"
"  FILE *fa=fopen(a,\"r\"), *fb=fopen(b,\"r\");\n"
"  if(!fa||!fb){ if(fa)fclose(fa); if(fb)fclose(fb); __exit_status=2; return; }\n"
"  int la=0,lb=0,ca,cb,diff=0;\n"
"  while(1){\n"
"    ca=fgetc(fa); cb=fgetc(fb);\n"
"    if(ca==EOF&&cb==EOF) break;\n"
"    if(ca!=cb){ diff=1; break; }\n"
"    if(ca=='\\n') la++;\n"
"    if(cb=='\\n') lb++;\n"
"  }\n"
"  fclose(fa); fclose(fb);\n"
"  __exit_status=diff?1:0;\n"
"}\n"
"\n"
"/* ---- search builtins ---- */\n"
"static void __attribute__((unused)) __b_find(const char *first,...){\n"
"  va_list ap; va_start(ap,first);\n"
"  char cmd[8192]=\"find\"; const char *p=first;\n"
"  while(p){ strncat(cmd,\" \",sizeof(cmd)-strlen(cmd)-1); strncat(cmd,p,sizeof(cmd)-strlen(cmd)-1); p=va_arg(ap,const char*); }\n"
"  va_end(ap); system(cmd);\n"
"}\n"
"static void __attribute__((unused)) __b_which(const char *cmd){ char *path=getenv(\"PATH\"); if(!path){return;} char *p=strdup(path); char *tok=strtok(p,\":\"); while(tok){ char full[4096]; snprintf(full,sizeof(full),\"%s/%s\",tok,cmd); if(access(full,X_OK)==0){ printf(\"%s\\n\",full); free(p); return; } tok=strtok(NULL,\":\"); } free(p); }\n"
"static void __attribute__((unused)) __b_whereis(const char *cmd){ char cmd2[1024]; snprintf(cmd2,sizeof(cmd2),\"whereis %s\",cmd); system(cmd2); }\n"
"static void __attribute__((unused)) __b_locate(const char *pat){ char cmd[1024]; snprintf(cmd,sizeof(cmd),\"locate %s\",pat); system(cmd); }\n"
"\n"
"/* ---- system info builtins ---- */\n"
"static void __attribute__((unused)) __b_date(const char *fmt){\n"
"  time_t t=time(NULL); struct tm *tm=localtime(&t);\n"
"  if(!fmt||!fmt[0]){ char b[256]; strftime(b,sizeof(b),\"%a %b %e %H:%M:%S %Z %Y\",tm); printf(\"%s\\n\",b); return; }\n"
"  if(fmt[0]=='+'){ char b[1024]; strftime(b,sizeof(b),fmt+1,tm); printf(\"%s\\n\",b); }\n"
"}\n"
"static void __attribute__((unused)) __b_whoami(void){ struct passwd *pw=getpwuid(getuid()); printf(\"%s\\n\",pw?pw->pw_name:\"unknown\"); }\n"
"static void __attribute__((unused)) __b_hostname(void){ char h[256]; if(gethostname(h,sizeof(h))==0) printf(\"%s\\n\",h); }\n"
"static void __attribute__((unused)) __b_hostname_set(const char *h){ if(sethostname(h,strlen(h))!=0) perror(\"hostname\"); }\n"
"static void __attribute__((unused)) __b_uname(int all){ struct utsname u; if(uname(&u)!=0){perror(\"uname\");return;} if(all) printf(\"%s %s %s %s %s\\n\",u.sysname,u.nodename,u.release,u.version,u.machine); else printf(\"%s\\n\",u.sysname); }\n"
"static void __attribute__((unused)) __b_arch(void){ struct utsname u; uname(&u); printf(\"%s\\n\",u.machine); }\n"
"static void __attribute__((unused)) __b_nproc(void){ long n=sysconf(_SC_NPROCESSORS_ONLN); printf(\"%ld\\n\",n); }\n"
"static void __attribute__((unused)) __b_id(void){ printf(\"uid=%d gid=%d\\n\",getuid(),getgid()); }\n"
"static void __attribute__((unused)) __b_env(void){ extern char **environ; for(char **e=environ;*e;e++) printf(\"%s\\n\",*e); }\n"
"static void __attribute__((unused)) __b_ps(void){ system(\"ps\"); }\n"
"static void __attribute__((unused)) __b_kill(const char *first,...){ va_list ap; va_start(ap,first); const char *p=first; char cmd[1024]=\"kill\"; while(p){ strncat(cmd,\" \",sizeof(cmd)-strlen(cmd)-1); strncat(cmd,p,sizeof(cmd)-strlen(cmd)-1); p=va_arg(ap,const char*); } va_end(ap); system(cmd); }\n"
"static void __attribute__((unused)) __b_wait(void){ int st; while(waitpid(-1,&st,WNOHANG)>0); }\n"
"static void __attribute__((unused)) __b_jobs(void){ /* stub */ }\n"
"static void __attribute__((unused)) __b_bg(void){ /* stub */ }\n"
"static void __attribute__((unused)) __b_fg(void){ /* stub */ }\n"
"static const char *__sh_trap_actions[32];\n"
"static int __sh_trap_is_func[32]={0};\n"
"static void (*__sh_trap_func[32])(int,char**)={NULL};\n"
"static void __b_trap_run(int sig){ if(sig>=0&&sig<32&&__sh_trap_actions[sig]&&__sh_trap_actions[sig][0]){ if(__sh_trap_is_func[sig]&&__sh_trap_func[sig]){ __sh_trap_func[sig](0,NULL); } else { system(__sh_trap_actions[sig]); } } }\n"
"static void __b_trap_exit_handler(void){ __b_trap_run(0); }\n"
"static void __b_trap_sighandler(int sig){ __b_trap_run(sig); }\n"
"static void __attribute__((unused)) __b_trap(const char *action,int sig){ if(!action||action[0]==0) return; if(sig<0||sig>=32) return; __sh_trap_actions[sig]=action; if(sig==0) atexit(__b_trap_exit_handler); else signal(sig,__b_trap_sighandler); }\n"
"static void __attribute__((unused)) __b_type(const char *cmd){ printf(\"%s is a shell builtin\\n\",cmd); }\n"
"static void __attribute__((unused)) __b_command(const char *first,...){ va_list ap; va_start(ap,first); char cmd[8192]; snprintf(cmd,sizeof(cmd),\"%s\",first); const char *p; while((p=va_arg(ap,const char*))!=NULL){ strncat(cmd,\" \",sizeof(cmd)-strlen(cmd)-1); strncat(cmd,p,sizeof(cmd)-strlen(cmd)-1); } va_end(ap); system(cmd); }\n"
"static void __attribute__((unused)) __b_alias(const char *a){ if(!a){ system(\"alias\"); return; } }\n"
"static void __attribute__((unused)) __b_unalias(const char *a){ (void)a; }\n"
"static void __attribute__((unused)) __b_history(void){ /* stub */ }\n"
"static void __attribute__((unused)) __b_pushd(const char *d){ char cwd[4096]; getcwd(cwd,sizeof(cwd)); chdir(d); }\n"
"static void __attribute__((unused)) __b_popd(void){ /* stub */ }\n"
"static void __attribute__((unused)) __b_dirs(void){ char cwd[4096]; getcwd(cwd,sizeof(cwd)); printf(\"%s\\n\",cwd); }\n"
"static void __attribute__((unused)) __b_seq(int s,int st,int e){ if(st>0) for(int i=s;i<=e;i+=st) printf(\"%d\\n\",i); else for(int i=s;i>=e;i+=st) printf(\"%d\\n\",i); }\n"
"static void __attribute__((unused)) __b_yes(const char *msg){ while(1){ printf(\"%s\\n\",msg?msg:\"y\"); fflush(stdout); } }\n"
"static void __attribute__((unused)) __b_source(const char *f){\n"
"  if(!f||!*f) return;\n"
"  FILE *fp=fopen(f,\"r\");\n"
"  if(!fp) return;\n"
"  char line[8192];\n"
"  while(fgets(line,sizeof(line),fp)){\n"
"    int l=(int)strlen(line);\n"
"    if(l>0&&line[l-1]=='\\n') line[l-1]=0;\n"
"    if(!line[0]||line[0]=='#') continue;\n"
"    /* try to handle VAR=value assignments inline (no system call) */\n"
"    char *eq=strchr(line,'=');\n"
"    if(eq && eq>line){\n"
"      /* check it's a simple assignment (no spaces before =) */\n"
"      char *sp=strchr(line,' ');\n"
"      if(!sp || sp>eq){\n"
"        *eq=0; char *val=eq+1;\n"
"        /* strip surrounding quotes from val */\n"
"        int vl=(int)strlen(val);\n"
"        if(vl>=2 && ((val[0]=='\"'&&val[vl-1]=='\"')||(val[0]=='\\''&&val[vl-1]=='\\''))){\n"
"          val[vl-1]=0; val++;\n"
"        }\n"
"        setenv(line,val,1);\n"
"        continue;\n"
"      }\n"
"    }\n"
"    /* for non-assignment lines, fall back to system */\n"
"    system(line);\n"
"  }\n"
"  fclose(fp);\n"
"}\n"
"static void __attribute__((unused)) __b_eval(const char **a){ char cmd[8192]=\"\"; for(const char **p=a;*p;p++){ if(*cmd) strncat(cmd,\" \",sizeof(cmd)-strlen(cmd)-1); strncat(cmd,*p,sizeof(cmd)-strlen(cmd)-1); } system(cmd); }\n"
"static void __attribute__((unused)) __b_nohup(const char *first,...){ va_list ap; va_start(ap,first); char cmd[8192]; snprintf(cmd,sizeof(cmd),\"nohup %s\",first); const char *p; while((p=va_arg(ap,const char*))!=NULL){ strncat(cmd,\" \",sizeof(cmd)-strlen(cmd)-1); strncat(cmd,p,sizeof(cmd)-strlen(cmd)-1); } va_end(ap); strncat(cmd,\" >/dev/null 2>&1 &\",sizeof(cmd)-strlen(cmd)-1); system(cmd); }\n"
"static void __attribute__((unused)) __b_time(const char *cmd){ clock_t t0=clock(); system(cmd); clock_t t1=clock(); fprintf(stderr,\"real %.3fs\\n\",(double)(t1-t0)/CLOCKS_PER_SEC); }\n"
"static void __attribute__((unused)) __b_free_mem(void){ system(\"free\"); }\n"
"static void __attribute__((unused)) __b_uptime(void){ system(\"uptime\"); }\n"
"static void __attribute__((unused)) __b_who(void){ system(\"who\"); }\n"
"static void __attribute__((unused)) __b_last(void){ system(\"last\"); }\n"
"static void __attribute__((unused)) __b_dmesg(void){ system(\"dmesg\"); }\n"
"static void __attribute__((unused)) __b_lsof(void){ system(\"lsof\"); }\n"
"static void __attribute__((unused)) __b_mount(void){ system(\"mount\"); }\n"
"static void __attribute__((unused)) __b_tty(void){ char *t=ttyname(0); printf(\"%s\\n\",t?t:\"not a tty\"); }\n"
"static void __attribute__((unused)) __b_help(void){\n"
"  printf(\"shell2c runtime — supported builtins:\\n\");\n"
"  printf(\"  echo printf cd pwd ls cat grep sed tr cut sort uniq wc head tail\\n\");\n"
"  printf(\"  cp mv rm mkdir rmdir touch ln chmod chown stat du df file\\n\");\n"
"  printf(\"  basename dirname realpath readlink mktemp install\\n\");\n"
"  printf(\"  tee xargs rev tac nl fold paste expand unexpand column shuf comm diff\\n\");\n"
"  printf(\"  find which whereis locate\\n\");\n"
"  printf(\"  date whoami hostname uname id env export unset set source eval\\n\");\n"
"  printf(\"  ps kill sleep wait jobs bg fg trap type command alias unalias\\n\");\n"
"  printf(\"  history pushd popd dirs seq yes true false test [ expr read exit\\n\");\n"
"  printf(\"  return clear reset nohup time free uptime who last dmesg lsof\\n\");\n"
"  printf(\"  mount arch nproc tty help\\n\");\n"
"}\n"
"/* ---- end runtime ---- */\n\n";

