/*
 * s2c_vm_runtime.c — VM runtime interpreter implementation
 *
 * The VM runtime is a string constant that gets emitted into the
 * generated C file. It contains:
 *   - VmValue tagged union (int/string/array)
 *   - Operand stack (4096 slots)
 *   - 8 registers (r0-r7)
 *   - Local variable slots
 *   - Const pool (string table)
 *   - Function table
 *   - Dispatch loop (switch-based)
 *   - Profiling counters for hot-path detection
 *   - JIT compilation trigger (template-based)
 *
 * Bytecode is XOR-encoded to prevent simple string extraction.
 *
 * Author: 爱摸鱼的狐狸 🦊 (VM extension)
 */
#include "s2c_vm_runtime.h"
#include <string.h>

/* The VM runtime C code — emitted into generated output files.
 *
 * This is a self-contained C implementation of the stack-based VM.
 * It uses switch-dispatch for portability.
 *
 * Key design choices:
 * 1. Bytecode is decoded at load time (XOR with 0x5A)
 * 2. Values are VmValue tagged unions
 * 3. Stack is a fixed-size array with a stack pointer
 * 4. Hot-path detection: each JMP target has a counter; when it
 *    exceeds JIT_HOT_THRESHOLD, the block is marked for JIT
 * 5. JIT: generates C source, compiles with system(gcc), dlopen's
 *    the .so, and calls the native function. Falls back to VM on error.
 */
const char *VM_RUNTIME =
"/* ---- Cshll VM runtime (stack-based) ---- */\n"
"#include <stdio.h>\n"
"#include <stdlib.h>\n"
"#include <string.h>\n"
"#include <ctype.h>\n"
"#include <unistd.h>\n"
"#include <stdint.h>\n"
"#include <time.h>\n"
"#include <dlfcn.h>\n"
"\n"
"/* Value types */\n"
"typedef enum { VM_NULL=0, VM_INT=1, VM_STR=2, VM_ARR=3 } VmType;\n"
"\n"
"/* Function table entry */\n"
"typedef struct {\n"
"    uint16_t name_idx;\n"
"    uint32_t entry;\n"
"    uint8_t nlocals;\n"
"    uint8_t nargs;\n"
"} VmFuncEntry;\n"
"\n"
"/* Tagged value */\n"
"typedef struct {\n"
"    VmType type;\n"
"    union {\n"
"        long ival;\n"
"        char *sval;\n"
"        struct { char **items; int count; int cap; } *aval;\n"
"    };\n"
"} VmValue;\n"
"\n"
"/* VM state */\n"
"static VmValue __vm_stack[4096];\n"
"static int __vm_sp = 0;\n"
"static VmValue __vm_regs[8] __attribute__((unused));\n"
"static VmValue __vm_locals[256] __attribute__((unused));\n"
"\n"
"/* Const pool and code — set by generated init */\n"
"static const char **__vm_consts;\n"
"static int __vm_nconsts;\n"
"static uint8_t *__vm_code;\n"
"static int __vm_code_size;\n"
"static uint8_t __vm_code_decoded[65536];\n"
"\n"
"/* Decode bytecode (double-layer XOR — matching bridge encoding) */\n"
"static void __vm_decode(const unsigned char *enc, int size) __attribute__((unused));\n"
"static void __vm_decode(const unsigned char *enc, int size){\n"
"    if(size>(int)sizeof(__vm_code_decoded)) size=(int)sizeof(__vm_code_decoded);\n"
"    for(int i=0;i<size;i++){\n"
"        uint8_t key2 = (uint8_t)(0xA5 ^ (i * 3) ^ ((i << 2) & 0x3F));\n"
"        uint8_t key1 = (uint8_t)(0x5A + i * 7 + (i >> 3) * 13);\n"
"        __vm_code_decoded[i] = (enc[i] ^ key2) ^ key1;\n"
"    }\n"
"}\n"
"\n"
"/* Function table */\n"
"typedef struct { uint16_t name_idx; uint32_t entry; uint8_t nlocals; uint8_t nargs; } VmFunc;\n"
"static VmFunc *__vm_funcs;\n"
"static int __vm_nfuncs;\n"
"\n"
"/* Profiling counters for hot-path detection */\n"
"static uint32_t __vm_profile[256];\n"
"static uint8_t __vm_jit_done[256];\n"
"\n"
"/* XOR key for bytecode decoding */\n"
"#define VM_XOR_KEY 0x5A\n"
"\n"
"/* ---- Value helpers ---- */\n"
"static VmValue vm_str(const char *s){\n"
"    VmValue v; v.type=VM_STR; v.sval=strdup(s?s:\"\"); return v;\n"
"}\n"
"static VmValue vm_int(long n){\n"
"    VmValue v; v.type=VM_INT; v.ival=n; return v;\n"
"}\n"
"static VmValue vm_null(void){\n"
"    VmValue v; v.type=VM_NULL; v.ival=0; return v;\n"
"}\n"
"\n"
"static void vm_free(VmValue *v){\n"
"    if(v->type==VM_STR && v->sval){ free(v->sval); v->sval=NULL; }\n"
"    else if(v->type==VM_ARR && v->aval){\n"
"        for(int i=0;i<v->aval->count;i++) free(v->aval->items[i]);\n"
"        free(v->aval->items); free(v->aval); v->aval=NULL;\n"
"    }\n"
"    v->type=VM_NULL;\n"
"}\n"
"\n"
"static long vm_to_int(VmValue *v){\n"
"    if(v->type==VM_INT) return v->ival;\n"
"    if(v->type==VM_STR) return v->sval ? atol(v->sval) : 0;\n"
"    return 0;\n"
"}\n"
"\n"
"static const char *vm_to_str(VmValue *v){\n"
"    if(v->type==VM_STR) return v->sval ? v->sval : \"\";\n"
"    if(v->type==VM_INT){\n"
"        char buf[32]; snprintf(buf,sizeof(buf),\"%ld\",v->ival);\n"
"        v->sval=strdup(buf); v->type=VM_STR;\n"
"        return v->sval;\n"
"    }\n"
"    return \"\";\n"
"}\n"
"\n"
"/* ---- Stack operations ---- */\n"
"static void vm_push(VmValue v){ if(__vm_sp<4096) __vm_stack[__vm_sp++]=v; }\n"
"static VmValue vm_pop(void){\n"
"    if(__vm_sp>0) return __vm_stack[--__vm_sp];\n"
"    return vm_null();\n"
"}\n"
"static VmValue *vm_peek(void) __attribute__((unused));\n"
"static VmValue *vm_peek(void){\n"
"    return (__vm_sp>0) ? &__vm_stack[__vm_sp-1] : NULL;\n"
"}\n"
"\n"
"/* ---- Call frame ---- */\n"
"typedef struct {\n"
"    uint32_t ret_addr;  /* return PC */\n"
"    int saved_sp;\n"
"    int saved_locals_base;\n"
"} VmFrame;\n"
"static VmFrame __vm_frames[256];\n"
"static int __vm_fp = 0;  /* frame pointer */\n"
"\n"
"/* ---- JIT compilation (template-based) ---- */\n"
"typedef void (*JitFn)(void);\n"
"static JitFn __vm_jit_table[256];\n"
"\n"
"static int vm_jit_compile(uint8_t *code, int start, int end, int block_id){\n"
"    /* Generate C source for the basic block, compile to .so, dlopen */\n"
"    char src_path[256], so_path[256], cmd[1024];\n"
"    snprintf(src_path,sizeof(src_path),\"/tmp/__vm_jit_%d.c\",block_id);\n"
"    snprintf(so_path,sizeof(so_path),\"/tmp/__vm_jit_%d.so\",block_id);\n"
"    FILE *f=fopen(src_path,\"w\");\n"
"    if(!f) return -1;\n"
"    fprintf(f,\"#include <stdio.h>\\n#include <stdlib.h>\\n#include <string.h>\\n\");\n"
"    fprintf(f,\"extern VmValue __vm_stack[]; extern int __vm_sp;\\n\");\n"
"    fprintf(f,\"extern VmValue __vm_locals[];\\n\");\n"
"    fprintf(f,\"extern const char **__vm_consts;\\n\");\n"
"    fprintf(f,\"void __vm_jit_entry_%d(void){\\n\",block_id);\n"
"    /* Emit native C for each opcode in the block */\n"
"    int pc=start;\n"
"    while(pc<end){\n"
"        uint8_t op=code[pc++];\n"
"        switch(op){\n"
"            case 0x01: { /* PUSH_STR */\n"
"                uint16_t idx=code[pc]|(code[pc+1]<<8); pc+=2;\n"
"                fprintf(f,\"{ VmValue v; v.type=VM_STR; v.sval=strdup(__vm_consts[%d]); if(__vm_sp<4096) __vm_stack[__vm_sp++]=v; }\\n\",idx);\n"
"                break; }\n"
"            case 0x02: { /* PUSH_INT */\n"
"                int32_t val=code[pc]|(code[pc+1]<<8)|(code[pc+2]<<16)|(code[pc+3]<<24); pc+=4;\n"
"                fprintf(f,\"{ VmValue v; v.type=VM_INT; v.ival=%d; if(__vm_sp<4096) __vm_stack[__vm_sp++]=v; }\\n\",val);\n"
"                break; }\n"
"            case 0x50: /* PRINT */\n"
"                fprintf(f,\"{ if(__vm_sp>0){ VmValue *p=&__vm_stack[__vm_sp-1]; if(p->type==VM_STR) fputs(p->sval?p->sval:\\\"\\\",stdout); else if(p->type==VM_INT) printf(\\\"%%ld\\\",p->ival); } }\\n\");\n"
"                break;\n"
"            case 0x51: /* PRINTLN */\n"
"                fprintf(f,\"{ if(__vm_sp>0){ VmValue *p=&__vm_stack[__vm_sp-1]; if(p->type==VM_STR) { fputs(p->sval?p->sval:\\\"\\\",stdout); } else if(p->type==VM_INT) printf(\\\"%%ld\\\",p->ival); } putchar('\\\\n'); __vm_sp--; }\\n\");\n"
"                break;\n"
"            case 0x04: /* POP */\n"
"                fprintf(f,\"{ if(__vm_sp>0) { vm_free(&__vm_stack[--__vm_sp]); } }\\n\");\n"
"                break;\n"
"            case 0x44: /* RET */\n"
"                fprintf(f,\"goto __vm_jit_end_%d;\\n\",block_id);\n"
"                break;\n"
"            case 0x46: /* HALT */\n"
"                fprintf(f,\"goto __vm_jit_end_%d;\\n\",block_id);\n"
"                break;\n"
"            default:\n"
"                /* Unsupported opcode in JIT — fall back to VM */\n"
"                fprintf(f,\"goto __vm_jit_end_%d;\\n\",block_id);\n"
"                pc=end;\n"
"                break;\n"
"        }\n"
"    }\n"
"    fprintf(f,\"__vm_jit_end_%d: return;\\n\",block_id);\n"
"    fprintf(f,\"}\\n\");\n"
"    fclose(f);\n"
"    snprintf(cmd,sizeof(cmd),\"gcc -O2 -shared -fPIC -o %s %s 2>/dev/null\",so_path,src_path);\n"
"    if(system(cmd)!=0){ unlink(src_path); return -1; }\n"
"    void *h=dlopen(so_path,RTLD_NOW|RTLD_GLOBAL);\n"
"    if(!h){ unlink(src_path); unlink(so_path); return -1; }\n"
"    char sym[64]; snprintf(sym,sizeof(sym),\"__vm_jit_entry_%d\",block_id);\n"
"    JitFn fn=(JitFn)dlsym(h,sym);\n"
"    if(!fn){ dlclose(h); unlink(src_path); unlink(so_path); return -1; }\n"
"    __vm_jit_table[block_id]=fn;\n"
"    __vm_jit_done[block_id]=1;\n"
"    unlink(src_path);\n"
"    /* Keep .so loaded via dlopen handle */\n"
"    return 0;\n"
"}\n"
"\n"
"/* ---- Main VM dispatch loop ---- */\n"
"static int __vm_opq_cnt = 0;\n"
"/* Opaque predicate: always returns true but looks data-dependent */\n"
"static int __vm_opq(int x){\n"
"    int r = x * 7 + 13;\n"
"    __vm_opq_cnt++;\n"
"    return (r & 1) || !(r & 1); /* tautology */\n"
"}\n"
"\n"
"/* Dead code decoy — looks meaningful but does nothing */\n"
"static int __vm_decoy(int seed){\n"
"    volatile int v = seed;\n"
"    v = (v ^ 0xAA) + ((v >> 3) & 0x1F);\n"
"    v = v * 31 + 17;\n"
"    (void)v;\n"
"    return seed;\n"
"}\n"
"\n"
"static int vm_run(uint32_t entry_pc){\n"
"    uint32_t pc = entry_pc;\n"
"    /* Anti-tamper: timing baseline */\n"
"    clock_t __vm_t0 = clock();\n"
"    /* Control flow flattening: main loop is a single switch dispatch */\n"
"    int __vm_state = 0; /* 0=fetch, 1=decode, 2=execute, 3=next */\n"
"    while(pc < (uint32_t)__vm_code_size){\n"
"        /* Opaque predicate check — injects false data dependency */\n"
"        if(!__vm_opq((int)pc)) { pc = 0; continue; }\n"
"        /* Dead code decoy — realistic but meaningless */\n"
"        __vm_decoy((int)(pc ^ 0x35));\n"
"        /* Anti-tamper: periodic timing check + stack integrity */\n"
"        if((__vm_opq_cnt & 0x3FF) == 0){\n"
"            clock_t __vm_t1 = clock();\n"
"            if((__vm_t1 - __vm_t0) > 5000000) { __vm_t0 = __vm_t1; }\n"
"            /* Stack integrity: checksum bottom 16 slots */\n"
"            unsigned int __vm_cksum = 0;\n"
"            for(int ci = 0; ci < 16 && ci < __vm_sp; ci++)\n"
"                __vm_cksum = __vm_cksum * 31 + (unsigned int)(uintptr_t)__vm_stack[ci].sval;\n"
"            /* If checksum changes unexpectedly, stack was tampered */\n"
"            static unsigned int __vm_prev_cksum = 0;\n"
"            if(__vm_prev_cksum && __vm_prev_cksum != __vm_cksum) {\n"
"                /* Stack modified externally — subtle corruption */\n"
"                __vm_sp = 0;\n"
"            }\n"
"            __vm_prev_cksum = __vm_cksum;\n"
"        }\n"
"        /* Flattened dispatch */\n"
"        __vm_state = 0;\n"
"        switch(__vm_state){\n"
"        case 0: /* fetch */\n"
"        {\n"
"        uint8_t op = __vm_code[pc++];\n"
"        /* Opaque predicate on opcode — always true */\n"
"        if(!__vm_opq(op)) { pc--; continue; }\n"
"        switch(op){\n"
"\n"
"        /* Stack operations */\n"
"        case 0x00: /* NOP */\n"
"            break;\n"
"        case 0x01: { /* PUSH_STR [u16 idx] */\n"
"            uint16_t idx = __vm_code[pc] | (__vm_code[pc+1]<<8); pc+=2;\n"
"            vm_push(vm_str(idx<__vm_nconsts ? __vm_consts[idx] : \"\"));\n"
"            break; }\n"
"        case 0x02: { /* PUSH_INT [i32] */\n"
"            int32_t val = __vm_code[pc] | (__vm_code[pc+1]<<8) |\n"
"                          (__vm_code[pc+2]<<16) | (__vm_code[pc+3]<<24); pc+=4;\n"
"            vm_push(vm_int(val));\n"
"            break; }\n"
"        case 0x03: { /* PUSH_VAR [u16 name_idx] */\n"
"            uint16_t idx = __vm_code[pc] | (__vm_code[pc+1]<<8); pc+=2;\n"
"            const char *name = idx<__vm_nconsts ? __vm_consts[idx] : \"\";\n"
"            const char *v = getenv(name);\n"
"            vm_push(vm_str(v?v:\"\"));\n"
"            break; }\n"
"        case 0x04: { /* POP */\n"
"            VmValue v = vm_pop(); vm_free(&v);\n"
"            break; }\n"
"        case 0x05: { /* DUP */\n"
"            if(__vm_sp>0){\n"
"                VmValue v = __vm_stack[__vm_sp-1];\n"
"                if(v.type==VM_STR) v.sval=strdup(v.sval?v.sval:\"\");\n"
"                vm_push(v);\n"
"            }\n"
"            break; }\n"
"        case 0x0B: /* PUSH_EMPTY */\n"
"            vm_push(vm_str(\"\"));\n"
"            break;\n"
"        case 0x0C: /* PUSH_ZERO */\n"
"            vm_push(vm_int(0));\n"
"            break;\n"
"\n"
"        /* Arithmetic */\n"
"        case 0x10: { /* ADD */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            if(a.type==VM_INT && b.type==VM_INT) vm_push(vm_int(a.ival+b.ival));\n"
"            else { /* string concat */\n"
"                const char *sa=vm_to_str(&a), *sb=vm_to_str(&b);\n"
"                char *r=malloc(strlen(sa)+strlen(sb)+1);\n"
"                strcpy(r,sa); strcat(r,sb);\n"
"                vm_push(vm_str(r));\n"
"            }\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x11: { /* SUB */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)-vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x12: { /* MUL */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)*vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x13: { /* DIV */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            long bv=vm_to_int(&b);\n"
"            vm_push(vm_int(bv!=0 ? vm_to_int(&a)/bv : 0));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x14: { /* MOD */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            long bv=vm_to_int(&b);\n"
"            vm_push(vm_int(bv!=0 ? vm_to_int(&a)%bv : 0));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x15: { /* INC */\n"
"            if(__vm_sp>0){\n"
"                VmValue *v=&__vm_stack[__vm_sp-1];\n"
"                if(v->type==VM_INT) v->ival++;\n"
"                else { long n=atol(v->sval?v->sval:\"\"); vm_free(v); *v=vm_int(n+1); }\n"
"            }\n"
"            break; }\n"
"        case 0x16: { /* DEC */\n"
"            if(__vm_sp>0){\n"
"                VmValue *v=&__vm_stack[__vm_sp-1];\n"
"                if(v->type==VM_INT) v->ival--;\n"
"                else { long n=atol(v->sval?v->sval:\"\"); vm_free(v); *v=vm_int(n-1); }\n"
"            }\n"
"            break; }\n"
"\n"
"        /* Comparison */\n"
"        case 0x20: { /* EQ */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            if(a.type==VM_INT && b.type==VM_INT) vm_push(vm_int(a.ival==b.ival));\n"
"            else vm_push(vm_int(strcmp(vm_to_str(&a),vm_to_str(&b))==0));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x21: { /* NE */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            if(a.type==VM_INT && b.type==VM_INT) vm_push(vm_int(a.ival!=b.ival));\n"
"            else vm_push(vm_int(strcmp(vm_to_str(&a),vm_to_str(&b))!=0));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x22: { /* LT */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)<vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x23: { /* GT */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)>vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x24: { /* LE */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)<=vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x25: { /* GE */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)>=vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x26: { /* NOT */\n"
"            VmValue a=vm_pop();\n"
"            vm_push(vm_int(!vm_to_int(&a)));\n"
"            vm_free(&a);\n"
"            break; }\n"
"\n"
"        /* String operations */\n"
"        case 0x30: { /* STRCAT */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            const char *sa=vm_to_str(&a), *sb=vm_to_str(&b);\n"
"            char *r=malloc(strlen(sa)+strlen(sb)+1);\n"
"            strcpy(r,sa); strcat(r,sb);\n"
"            vm_push(vm_str(r));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x31: { /* STRLEN */\n"
"            VmValue a=vm_pop();\n"
"            vm_push(vm_int((long)strlen(vm_to_str(&a))));\n"
"            vm_free(&a);\n"
"            break; }\n"
"        case 0x32: { /* SUBSTR — pop len, off, str; push substring */\n"
"            VmValue vl=vm_pop(), vo=vm_pop(), vs=vm_pop();\n"
"            int len=(int)vm_to_int(&vl), off=(int)vm_to_int(&vo);\n"
"            const char *s=vm_to_str(&vs); int slen=(int)strlen(s);\n"
"            if(off<0) off+=slen;\n"
"            if(off<0) off=0;\n"
"            if(off>slen) off=slen;\n"
"            if(len<0) len=slen-off;\n"
"            char *r=malloc(len+1); memcpy(r,s+off,len); r[len]=0;\n"
"            vm_push(vm_str(r));\n"
"            vm_free(&vs); vm_free(&vo); vm_free(&vl);\n"
"            break; }\n"
"        case 0x33: { /* STRCMP — push 0 if match (shell semantics) */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int((long)strcmp(vm_to_str(&a),vm_to_str(&b))));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x34: { /* TOUPPER */\n"
"            VmValue a=vm_pop(); const char *s=vm_to_str(&a);\n"
"            char *r=malloc(strlen(s)+1); int i=0;\n"
"            for(; s[i]; i++) r[i]=toupper((unsigned char)s[i]);\n"
"            r[i]=0;\n"
"            vm_push(vm_str(r)); vm_free(&a);\n"
"            break; }\n"
"        case 0x35: { /* TOLOWER */\n"
"            VmValue a=vm_pop(); const char *s=vm_to_str(&a);\n"
"            char *r=malloc(strlen(s)+1); int i=0;\n"
"            for(; s[i]; i++) r[i]=tolower((unsigned char)s[i]);\n"
"            r[i]=0;\n"
"            vm_push(vm_str(r)); vm_free(&a);\n"
"            break; }\n"
"        case 0x80: { /* TO_INT */\n"
"            VmValue a=vm_pop();\n"
"            long n=vm_to_int(&a);\n"
"            vm_free(&a);\n"
"            vm_push(vm_int(n));\n"
"            break; }\n"
"        case 0x81: { /* TO_STR */\n"
"            if(__vm_sp>0){\n"
"                VmValue *v=&__vm_stack[__vm_sp-1];\n"
"                if(v->type==VM_INT){\n"
"                    char buf[32]; snprintf(buf,sizeof(buf),\"%ld\",v->ival);\n"
"                    v->sval=strdup(buf); v->type=VM_STR;\n"
"                }\n"
"            }\n"
"            break; }\n"
"\n"
"        /* Control flow */\n"
"        case 0x40: { /* JMP [u16 target] */\n"
"            uint16_t target=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            /* Profiling: count jumps to this target */\n"
"            if(target<256){\n"
"                __vm_profile[target]++;\n"
"                /* Find end of basic block (for both JIT and native call) */\n"
"                int end=target+1;\n"
"                while(end<(int)__vm_code_size &&\n"
"                      __vm_code[end]!=0x40 && /* JMP */\n"
"                      __vm_code[end]!=0x41 && /* JZ */\n"
"                      __vm_code[end]!=0x42 && /* JNZ */\n"
"                      __vm_code[end]!=0x44 && /* RET */\n"
"                      __vm_code[end]!=0x46)  /* HALT */\n"
"                    end++;\n"
"                /* Hot path detection: trigger JIT */\n"
"                if(__vm_profile[target]>=100 && !__vm_jit_done[target]){\n"
"                    vm_jit_compile(__vm_code,target,end,target);\n"
"                }\n"
"                /* If JIT'd, call native */\n"
"                if(__vm_jit_done[target] && __vm_jit_table[target]){\n"
"                    __vm_jit_table[target]();\n"
"                    /* After native execution, continue from after block */\n"
"                    pc=end;\n"
"                    continue;\n"
"                }\n"
"            }\n"
"            pc=target;\n"
"            break; }\n"
"        case 0x41: { /* JZ [u16 target] */\n"
"            uint16_t target=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            VmValue cond=vm_pop();\n"
"            int is_zero = !vm_to_int(&cond);\n"
"            vm_free(&cond);\n"
"            if(is_zero) pc=target;\n"
"            break; }\n"
"        case 0x42: { /* JNZ [u16 target] */\n"
"            uint16_t target=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            VmValue cond=vm_pop();\n"
"            int is_true = vm_to_int(&cond);\n"
"            vm_free(&cond);\n"
"            if(is_true) pc=target;\n"
"            break; }\n"
"        case 0x43: { /* CALL [u16 func_idx] */\n"
"            uint16_t fi=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            if(fi<__vm_nfuncs && __vm_fp<256){\n"
"                __vm_frames[__vm_fp].ret_addr=pc;\n"
"                __vm_frames[__vm_fp].saved_sp=__vm_sp;\n"
"                __vm_fp++;\n"
"                pc=__vm_funcs[fi].entry;\n"
"            }\n"
"            break; }\n"
"        case 0x44: { /* RET */\n"
"            if(__vm_fp>0){\n"
"                __vm_fp--;\n"
"                pc=__vm_frames[__vm_fp].ret_addr;\n"
"            }\n"
"            break; }\n"
"        case 0x46: { /* HALT */\n"
"            VmValue v=vm_pop();\n"
"            int code=(int)vm_to_int(&v);\n"
"            vm_free(&v);\n"
"            return code;\n"
"            break; }\n"
"\n"
"        /* I/O */\n"
"        case 0x50: { /* PRINT */\n"
"            if(__vm_sp>0){\n"
"                VmValue *v=&__vm_stack[__vm_sp-1];\n"
"                const char *s=vm_to_str(v);\n"
"                fputs(s,stdout);\n"
"            }\n"
"            break; }\n"
"        case 0x51: { /* PRINTLN */\n"
"            if(__vm_sp>0){\n"
"                VmValue v=vm_pop();\n"
"                const char *s=vm_to_str(&v);\n"
"                fputs(s,stdout);\n"
"                vm_free(&v);\n"
"            }\n"
"            putchar('\\n');\n"
"            break; }\n"
"        case 0x52: { /* PRINT_INT */\n"
"            if(__vm_sp>0){\n"
"                VmValue v=vm_pop();\n"
"                printf(\"%ld\",vm_to_int(&v));\n"
"                vm_free(&v);\n"
"            }\n"
"            break; }\n"
"\n"
"        /* Shell interop */\n"
"        case 0x60: { /* EXEC_CMD */\n"
"            VmValue cmd=vm_pop();\n"
"            const char *s=vm_to_str(&cmd);\n"
"            int rc=system(s);\n"
"            vm_push(vm_int((long)rc));\n"
"            vm_free(&cmd);\n"
"            break; }\n"
"        case 0x61: { /* EXEC_PIPE — pop two cmds, pipe left|right */\n"
"            VmValue right=vm_pop(), left=vm_pop();\n"
"            const char *sl=vm_to_str(&left), *sr=vm_to_str(&right);\n"
"            char cmd[8192];\n"
"            snprintf(cmd,sizeof(cmd),\"%s | %s\",sl,sr);\n"
"            int rc=system(cmd);\n"
"            vm_push(vm_int((long)rc));\n"
"            vm_free(&left); vm_free(&right);\n"
"            break; }\n"
"        case 0x62: { /* GETENV */\n"
"            VmValue name=vm_pop();\n"
"            const char *v=getenv(vm_to_str(&name));\n"
"            vm_push(vm_str(v?v:\"\"));\n"
"            vm_free(&name);\n"
"            break; }\n"
"        case 0x63: { /* SETENV */\n"
"            VmValue val=vm_pop(), name=vm_pop();\n"
"            setenv(vm_to_str(&name),vm_to_str(&val),1);\n"
"            vm_free(&name); vm_free(&val);\n"
"            break; }\n"
"        case 0x64: { /* EXIT */\n"
"            VmValue v=vm_pop();\n"
"            int code=(int)vm_to_int(&v);\n"
"            vm_free(&v);\n"
"            exit(code);\n"
"            break; }\n"
"\n"
"        /* Array operations */\n"
"        case 0x70: { /* ARR_NEW */\n"
"            VmValue v; v.type=VM_ARR;\n"
"            v.aval=malloc(sizeof(*v.aval));\n"
"            v.aval->items=NULL; v.aval->count=0; v.aval->cap=0;\n"
"            vm_push(v);\n"
"            break; }\n"
"        case 0x71: { /* ARR_PUSH */\n"
"            VmValue elem=vm_pop();\n"
"            if(__vm_sp>0 && __vm_stack[__vm_sp-1].type==VM_ARR){\n"
"                VmValue *arr=&__vm_stack[__vm_sp-1];\n"
"                if(arr->aval->count>=arr->aval->cap){\n"
"                    arr->aval->cap=arr->aval->cap?arr->aval->cap*2:8;\n"
"                    arr->aval->items=realloc(arr->aval->items,arr->aval->cap*sizeof(char*));\n"
"                }\n"
"                arr->aval->items[arr->aval->count++]=strdup(vm_to_str(&elem));\n"
"            }\n"
"            vm_free(&elem);\n"
"            break; }\n"
"        case 0x72: { /* ARR_GET */\n"
"            VmValue idx=vm_pop();\n"
"            if(__vm_sp>0 && __vm_stack[__vm_sp-1].type==VM_ARR){\n"
"                VmValue *arr=&__vm_stack[__vm_sp-1];\n"
"                int i=(int)vm_to_int(&idx);\n"
"                if(i>=0 && i<arr->aval->count)\n"
"                    vm_push(vm_str(arr->aval->items[i]));\n"
"                else\n"
"                    vm_push(vm_str(\"\"));\n"
"                vm_free(&__vm_stack[__vm_sp-2]);\n"
"                __vm_stack[__vm_sp-2]=__vm_stack[__vm_sp-1];\n"
"                __vm_sp--;\n"
"            } else vm_push(vm_str(\"\"));\n"
"            vm_free(&idx);\n"
"            break; }\n"
"        case 0x73: { /* ARR_LEN */\n"
"            if(__vm_sp>0 && __vm_stack[__vm_sp-1].type==VM_ARR){\n"
"                VmValue *arr=&__vm_stack[__vm_sp-1];\n"
"                int n=arr->aval->count;\n"
"                vm_free(arr);\n"
"                *arr=vm_int(n);\n"
"            }\n"
"            break; }\n"
"        case 0x74: { /* ARR_JOIN */\n"
"            if(__vm_sp>0 && __vm_stack[__vm_sp-1].type==VM_ARR){\n"
"                VmValue *arr=&__vm_stack[__vm_sp-1];\n"
"                int total=0;\n"
"                for(int i=0;i<arr->aval->count;i++)\n"
"                    total+=strlen(arr->aval->items[i])+1;\n"
"                char *r=malloc(total+1); r[0]=0;\n"
"                for(int i=0;i<arr->aval->count;i++){\n"
"                    if(i>0) strcat(r,\" \");\n"
"                    strcat(r,arr->aval->items[i]);\n"
"                }\n"
"                vm_free(arr);\n"
"                *arr=vm_str(r);\n"
"            }\n"
"            break; }\n"
"\n"
"        /* Profiling */\n"
"        case 0xF0: { /* PROFILE [u16 block_id] */\n"
"            uint16_t bid=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            if(bid<256){\n"
"                __vm_profile[bid]++;\n"
"                if(__vm_profile[bid]>=100 && !__vm_jit_done[bid]){\n"
"                    /* Find end of basic block */\n"
"                    int end=pc;\n"
"                    while(end<(int)__vm_code_size &&\n"
"                          __vm_code[end]!=0x40 &&\n"
"                          __vm_code[end]!=0x41 &&\n"
"                          __vm_code[end]!=0x42 &&\n"
"                          __vm_code[end]!=0x44 &&\n"
"                          __vm_code[end]!=0x46)\n"
"                        end++;\n"
"                    vm_jit_compile(__vm_code,pc,end,bid);\n"
"                    if(__vm_jit_done[bid] && __vm_jit_table[bid]){\n"
"                        __vm_jit_table[bid]();\n"
"                        pc=end;\n"
"                        continue;\n"
"                    }\n"
"                }\n"
"            }\n"
"            break; }\n"
"\n"
"        default:\n"
"            /* Unknown opcode — halt with decoy computation */\n"
"            __vm_decoy(op);\n"
"            fprintf(stderr,\"VM: unknown opcode 0x%02x at pc=%u\\n\",op,pc-1);\n"
"            return 1;\n"
"        }\n"
"        /* End of inner switch */\n"
"        break;\n"
"        default: /* unreachable flattened state */\n"
"            __vm_decoy(__vm_state);\n"
"            break;\n"
"        }\n"
"        /* End of flattened dispatch */\n"
"        }\n"
"    }\n"
"    return 0;\n"
"}\n"
;

void emit_vm_runtime(FILE *out){
    fprintf(out, "%s", VM_RUNTIME);
}

void emit_vm_const_pool(FILE *out, const char **consts, int nconsts){
    fprintf(out, "static const char *__vm_const_data[] = {\n");
    for(int i=0; i<nconsts; i++){
        /* Escape for C string literal */
        fprintf(out, "    \"");
        for(const char *c = consts[i]; c && *c; c++){
            if(*c=='"') fprintf(out,"\\\"");
            else if(*c=='\\') fprintf(out,"\\\\");
            else if(*c=='\n') fprintf(out,"\\n");
            else if(*c=='\t') fprintf(out,"\\t");
            else if(*c=='\r') fprintf(out,"\\r");
            else fprintf(out,"%c",*c);
        }
        fprintf(out, "\",\n");
    }
    fprintf(out, "    NULL\n};\n");
    fprintf(out, "#define __VM_NCONSTS %d\n", nconsts);
}

void emit_vm_code(FILE *out, const uint8_t *code, int len){
    /* XOR-encode bytecode to prevent trivial extraction */
    fprintf(out, "static uint8_t __vm_code_encoded[] = {\n");
    for(int i=0; i<len; i++){
        if(i%16==0) fprintf(out, "    ");
        fprintf(out, "0x%02x", code[i] ^ 0x5A);
        if(i<len-1) fprintf(out, ",");
        if(i%16==15 || i==len-1) fprintf(out, "\n");
    }
    fprintf(out, "};\n");
    fprintf(out, "#define __VM_CODE_SIZE %d\n", len);
    /* Decode at runtime: XOR back */
    fprintf(out, "static uint8_t __vm_code_decoded[%d];\n", len);
    fprintf(out, "static void __vm_decode(void){\n");
    fprintf(out, "    for(int i=0;i<%d;i++) __vm_code_decoded[i]=__vm_code_encoded[i]^0x5A;\n", len);
    fprintf(out, "}\n");
}

void emit_vm_func_table(FILE *out, const VmFuncEntry *funcs, int nfuncs,
                        const char **const_pool){
    fprintf(out, "static VmFunc __vm_func_table[] = {\n");
    for(int i=0; i<nfuncs; i++){
        fprintf(out, "    {%d,%u,%d,%d},\n",
                funcs[i].name_idx, funcs[i].entry,
                funcs[i].nlocals, funcs[i].nargs);
    }
    fprintf(out, "    {0,0,0,0}\n};\n");
    fprintf(out, "#define __VM_NFUNCS %d\n", nfuncs);
}

void emit_vm_main(FILE *out){
    fprintf(out, "/* ---- VM entry point ---- */\n");
    fprintf(out, "int main(int argc, char **argv){\n");
    fprintf(out, "    setvbuf(stdout,NULL,_IONBF,0);\n");
    fprintf(out, "    __vm_consts = __vm_const_data;\n");
    fprintf(out, "    __vm_nconsts = __VM_NCONSTS;\n");
    fprintf(out, "    __vm_decode();\n");
    fprintf(out, "    __vm_code = __vm_code_decoded;\n");
    fprintf(out, "    __vm_code_size = __VM_CODE_SIZE;\n");
    fprintf(out, "    __vm_funcs = __vm_func_table;\n");
    fprintf(out, "    __vm_nfuncs = __VM_NFUNCS;\n");
    fprintf(out, "    /* Set $0-$9 from argv */\n");
    for(int i=0; i<10; i++){
        fprintf(out, "    if(argc>%d) setenv(\"%d\",argv[%d],1);\n", i, i, i);
    }
    fprintf(out, "    int rc = vm_run(0);\n");
    fprintf(out, "    return rc;\n");
    fprintf(out, "}\n");
}
