/*
 * s2c_vm_runtime.c — VM runtime interpreter implementation
 *
 * The VM runtime is a string constant that gets emitted into the
 * generated C file. It contains:
 *   - VmValue tagged union (int/string/array)
 *   - Operand stack (4096 slots)
 *   - 8 registers (r0-r7)
 *   - Local variable slots
 *   - Const pool (string table)
 *   - Function table
 *   - Dispatch loop (switch-based)
 *   - Profiling counters for hot-path detection
 *   - JIT compilation trigger (template-based)
 *
 * Bytecode is XOR-encoded to prevent simple string extraction.
 *
 * Author: 爱摸鱼的狐狸 🦊 (VM extension)
 */
#include "s2c_vm_runtime.h"
#include <string.h>

/* The VM runtime C code — emitted into generated output files.
 *
 * This is a self-contained C implementation of the stack-based VM.
 * It uses switch-dispatch for portability.
 *
 * Key design choices:
 * 1. Bytecode is decoded at load time (XOR with 0x5A)
 * 2. Values are VmValue tagged unions
 * 3. Stack is a fixed-size array with a stack pointer
 * 4. Hot-path detection: each JMP target has a counter; when it
 *    exceeds JIT_HOT_THRESHOLD, the block is marked for JIT
 * 5. JIT: generates C source, compiles with system(gcc), dlopen's
 *    the .so, and calls the native function. Falls back to VM on error.
 */
const char *VM_RUNTIME =
"/* ---- Cshll VM runtime (stack-based) ---- */\n"
"#include <stdio.h>\n"
"#include <stdlib.h>\n"
"#include <string.h>\n"
"#include <ctype.h>\n"
"#include <unistd.h>\n"
"#include <stdint.h>\n"
"#include <time.h>\n"
"#include <dlfcn.h>\n"
"#include <malloc.h>\n"
"#include <sys/mman.h>\n"
"#include <sys/stat.h>\n"
"#include <sys/wait.h>\n"
"\n"
"/* Anti-analysis: resolve libc functions via dlsym to hide PLT entries */\n"
"typedef int (*_sys_fn)(const char*);\n"
"typedef int (*_setenv_fn)(const char*,const char*,int);\n"
"typedef char* (*_getenv_fn)(const char*);\n"
"typedef void* (*_malloc_fn)(size_t);\n"
"typedef void (*_free_fn)(void*);\n"
"typedef int (*_putchar_fn)(int);\n"
"static _sys_fn _x_sys=NULL;\n"
"static _setenv_fn _x_se=NULL;\n"
"static _getenv_fn _x_ge=NULL;\n"
"static _malloc_fn _x_ma=NULL;\n"
"static _free_fn _x_fr=NULL;\n"
"static void _x_init(void){\n"
"    /* Encoded function names (XOR 0x3C) */\n"
"    static char _n1[]={0x4F,0x45,0x4F,0x48,0x59,0x51,0x00}; /* system */\n"
"    static char _n2[]={0x4F,0x59,0x48,0x59,0x52,0x4A,0x00}; /* setenv */\n"
"    static char _n3[]={0x5B,0x59,0x48,0x59,0x52,0x4A,0x00}; /* getenv */\n"
"    static char _n4[]={0x51,0x5D,0x50,0x50,0x53,0x5F,0x00}; /* malloc */\n"
"    static char _n5[]={0x5A,0x4E,0x59,0x59,0x00}; /* free */\n"
"    for(int i=0;_n1[i];i++) _n1[i]^=0x3C;\n"
"    for(int i=0;_n2[i];i++) _n2[i]^=0x3C;\n"
"    for(int i=0;_n3[i];i++) _n3[i]^=0x3C;\n"
"    for(int i=0;_n4[i];i++) _n4[i]^=0x3C;\n"
"    for(int i=0;_n5[i];i++) _n5[i]^=0x3C;\n"
"    _x_sys=(_sys_fn)dlsym(RTLD_DEFAULT,_n1);\n"
"    _x_se=(_setenv_fn)dlsym(RTLD_DEFAULT,_n2);\n"
"    _x_ge=(_getenv_fn)dlsym(RTLD_DEFAULT,_n3);\n"
"    _x_ma=(_malloc_fn)dlsym(RTLD_DEFAULT,_n4);\n"
"    _x_fr=(_free_fn)dlsym(RTLD_DEFAULT,_n5);\n"
"}\n"
"/* Wrapper macros */\n"
"#define _sys(s) (_x_sys?(void)_x_sys(s):(void)0)\n"
"#define _setenv(n,v,o) (_x_se?_x_se(n,v,o):0)\n"
"#define _getenv(n) (_x_ge?_x_ge(n):(char*)0)\n"
"#define _malloc(s) (_x_ma?_x_ma(s):(void*)0)\n"
"#define _free(p) (_x_fr?_x_fr(p):(void)0)\n"
"\n"
"/* Value types */\n"
"typedef enum { VM_NULL=0, VM_INT=1, VM_STR=2, VM_ARR=3 } VmType;\n"
"\n"
"/* Function table entry */\n"
"typedef struct {\n"
"    uint16_t name_idx;\n"
"    uint32_t entry;\n"
"    uint8_t nlocals;\n"
"    uint8_t nargs;\n"
"} VmFuncEntry;\n"
"\n"
"/* Tagged value */\n"
"typedef struct {\n"
"    VmType type;\n"
"    union {\n"
"        long ival;\n"
"        char *sval;\n"
"        struct { char **items; int count; int cap; } *aval;\n"
"    };\n"
"} VmValue;\n"
"\n"
"/* VM state */\n"
"static VmValue __vm_stack[4096];\n"
"static int __vm_sp = 0;\n"
"static VmValue __vm_regs[8] __attribute__((unused));\n"
"static VmValue __vm_locals[256] __attribute__((unused));\n"
"\n"
"/* Const pool: encoded data kept in memory, decrypted on-demand per access */\n"
"static const unsigned char **__vm_cp_enc_ptrs; /* points to encoded length+bytes for each string */\n"
"static int __vm_nconsts;\n"
"static uint8_t *__vm_code;\n"
"static int __vm_code_size;\n"
"static uint8_t __vm_code_decoded[65536];\n"
"\n"
"/* On-demand constant decryption: decrypt one constant at a time into a small scratch buffer,\n"
" * use it, then wipe it. The full plaintext is never fully resident in memory. */\n"
"static char __vm_const_scratch[512];\n"
"static int __vm_const_used = -1;\n"
"\n"
"/* Runtime key — set during init */\n"
"static uint32_t __vm_rt_key_val = 0;\n"
"\n"
"/* Decrypt constant #idx into scratch buffer */\n"
"static const char *__vm_const_get(int idx){\n"
"    if(idx<0||idx>=__vm_nconsts) return \"\";\n"
"    if(idx==__vm_const_used) return __vm_const_scratch;\n"
"    /* Wipe previous */\n"
"    if(__vm_const_used>=0) memset(__vm_const_scratch,0,sizeof(__vm_const_scratch));\n"
"    /* Decrypt from encoded pool */\n"
"    const unsigned char *enc = __vm_cp_enc_ptrs[idx];\n"
"    if(!enc) return \"\";\n"
"    uint32_t rt = __vm_rt_key_val;\n"
"    uint8_t key = (uint8_t)((rt >> ((idx % 4) * 8)) ^ (idx * 0x3D + 0x17));\n"
"    int slen = enc[0] ^ key;\n"
"    if(slen > (int)sizeof(__vm_const_scratch)-1) slen = (int)sizeof(__vm_const_scratch)-1;\n"
"    if(slen < 0) slen = 0;\n"
"    for(int j = 0; j < slen; j++){\n"
"        uint8_t k1 = (uint8_t)((rt >> (((idx + j) % 4) * 8)) ^ (j * 0x5B));\n"
"        uint8_t k2 = (uint8_t)((rt ^ (idx * 0x1F + j * 0x2D)) >> ((j % 4) * 8));\n"
"        __vm_const_scratch[j] = enc[1+j] ^ k1 ^ k2;\n"
"    }\n"
"    __vm_const_scratch[slen] = 0;\n"
"    __vm_const_used = idx;\n"
"    return __vm_const_scratch;\n"
"}\n"
"static void __vm_const_wipe(){\n"
"    if(__vm_const_used>=0){ memset(__vm_const_scratch,0,sizeof(__vm_const_scratch)); __vm_const_used=-1; }\n"
"}\n"
"\n"
"/* Output capture buffer for $(func args) */\n"
"static char __vm_cap_buf[65536];\n"
"static int __vm_cap_len = 0;\n"
"static int __vm_cap_mode = 0;\n"
"\n"
"/* Decode bytecode (double-layer XOR — matching bridge encoding) */\n"
"static void __vm_decode(const unsigned char *enc, int size) __attribute__((unused));\n"
"static void __vm_decode(const unsigned char *enc, int size){\n"
"    if(size>(int)sizeof(__vm_code_decoded)) size=(int)sizeof(__vm_code_decoded);\n"
"    for(int i=0;i<size;i++){\n"
"        uint8_t key2 = (uint8_t)(0xA5 ^ (i * 3) ^ ((i << 2) & 0x3F));\n"
"        uint8_t key1 = (uint8_t)(0x5A + i * 7 + (i >> 3) * 13);\n"
"        __vm_code_decoded[i] = (enc[i] ^ key2) ^ key1;\n"
"    }\n"
"}\n"
"\n"
"/* Function table */\n"
"typedef struct { uint16_t name_idx; uint32_t entry; uint8_t nlocals; uint8_t nargs; } VmFunc;\n"
"static VmFunc *__vm_funcs;\n"
"static int __vm_nfuncs;\n"
"\n"
"/* Profiling counters for hot-path detection */\n"
"static uint32_t __vm_profile[256];\n"
"static uint8_t __vm_jit_done[256];\n"
"\n"
"/* XOR key for bytecode decoding */\n"
"#define VM_XOR_KEY 0x5A\n"
"\n"
"/* ---- Value helpers ---- */\n"
"static VmValue vm_str(const char *s){\n"
"    VmValue v; v.type=VM_STR; v.sval=strdup(s?s:\"\"); return v;\n"
"}\n"
"static VmValue vm_int(long n){\n"
"    VmValue v; v.type=VM_INT; v.ival=n; return v;\n"
"}\n"
"static VmValue vm_null(void){\n"
"    VmValue v; v.type=VM_NULL; v.ival=0; return v;\n"
"}\n"
"\n"
"static void vm_free(VmValue *v){\n"
"    if(v->type==VM_STR && v->sval){ _free(v->sval); v->sval=NULL; }\n"
"    else if(v->type==VM_ARR && v->aval){\n"
"        for(int i=0;i<v->aval->count;i++) _free(v->aval->items[i]);\n"
"        _free(v->aval->items); _free(v->aval); v->aval=NULL;\n"
"    }\n"
"    v->type=VM_NULL;\n"
"}\n"
"\n"
"static long vm_to_int(VmValue *v){\n"
"    if(v->type==VM_INT) return v->ival;\n"
"    if(v->type==VM_STR) return v->sval ? atol(v->sval) : 0;\n"
"    return 0;\n"
"}\n"
"\n"
"static const char *vm_to_str(VmValue *v){\n"
"    if(v->type==VM_STR) return v->sval ? v->sval : \"\";\n"
"    if(v->type==VM_INT){\n"
"        char buf[32]; snprintf(buf,sizeof(buf),\"%ld\",v->ival);\n"
"        v->sval=strdup(buf); v->type=VM_STR;\n"
"        return v->sval;\n"
"    }\n"
"    return \"\";\n"
"}\n"
"\n"
"/* ---- Stack operations ---- */\n"
"static void vm_push(VmValue v){ if(__vm_sp<4096) __vm_stack[__vm_sp++]=v; }\n"
"static VmValue vm_pop(void){\n"
"    if(__vm_sp>0) return __vm_stack[--__vm_sp];\n"
"    return vm_null();\n"
"}\n"
"static VmValue *vm_peek(void) __attribute__((unused));\n"
"static VmValue *vm_peek(void){\n"
"    return (__vm_sp>0) ? &__vm_stack[__vm_sp-1] : NULL;\n"
"}\n"
"\n"
"/* ---- Call frame ---- */\n"
"typedef struct {\n"
"    uint32_t ret_addr;  /* return PC */\n"
"    int saved_sp;\n"
"    int saved_locals_base;\n"
"} VmFrame;\n"
"static VmFrame __vm_frames[256];\n"
"static int __vm_fp = 0;  /* frame pointer */\n"
"\n"
"/* ---- JIT compilation (template-based) ---- */\n"
"typedef void (*JitFn)(void);\n"
"static JitFn __vm_jit_table[256];\n"
"\n"
"static int vm_jit_compile(uint8_t *code, int start, int end, int block_id){\n"
"    /* Generate C source for the basic block, compile to .so, dlopen */\n"
"    char src_path[256], so_path[256], cmd[1024];\n"
"    /* Obfuscated paths to avoid .rodata leak of JIT mechanism */\n"
"    char _tmp_pfx[16]; _tmp_pfx[0]='/';_tmp_pfx[1]='t';_tmp_pfx[2]='m';_tmp_pfx[3]='p';_tmp_pfx[4]='/';_tmp_pfx[5]='_';_tmp_pfx[6]='Q';_tmp_pfx[7]=0;\n"
"    snprintf(src_path,sizeof(src_path),\"%sj%d.c\",_tmp_pfx,block_id);\n"
"    snprintf(so_path,sizeof(so_path),\"%sj%d.so\",_tmp_pfx,block_id);\n"
"    FILE *f=fopen(src_path,\"w\");\n"
"    if(!f) return -1;\n"
"    /* Obfuscated JIT template strings — assembled at runtime to avoid plaintext in .rodata */\n"
"    volatile char _jit_p1[32]; _jit_p1[0]='#'; _jit_p1[1]='i'; _jit_p1[2]='n'; _jit_p1[3]='c'; _jit_p1[4]='l'; _jit_p1[5]='u'; _jit_p1[6]='d'; _jit_p1[7]='e'; _jit_p1[8]=' '; _jit_p1[9]='<'; _jit_p1[10]='s'; _jit_p1[11]='t'; _jit_p1[12]='d'; _jit_p1[13]='i'; _jit_p1[14]='o'; _jit_p1[15]='.'; _jit_p1[16]='h'; _jit_p1[17]='>'; _jit_p1[18]='\\n'; _jit_p1[19]=0;\n"
"    volatile char _jit_p2[64]; _jit_p2[0]='#'; _jit_p2[1]='i'; _jit_p2[2]='n'; _jit_p2[3]='c'; _jit_p2[4]='l'; _jit_p2[5]='u'; _jit_p2[6]='d'; _jit_p2[7]='e'; _jit_p2[8]=' '; _jit_p2[9]='<'; _jit_p2[10]='s'; _jit_p2[11]='t'; _jit_p2[12]='d'; _jit_p2[13]='l'; _jit_p2[14]='i'; _jit_p2[15]='b'; _jit_p2[16]='.'; _jit_p2[17]='h'; _jit_p2[18]='>'; _jit_p2[19]='\\n'; _jit_p2[20]='#'; _jit_p2[21]='i'; _jit_p2[22]='n'; _jit_p2[23]='c'; _jit_p2[24]='l'; _jit_p2[25]='u'; _jit_p2[26]='d'; _jit_p2[27]='e'; _jit_p2[28]=' '; _jit_p2[29]='<'; _jit_p2[30]='s'; _jit_p2[31]='t'; _jit_p2[32]='r'; _jit_p2[33]='i'; _jit_p2[34]='n'; _jit_p2[35]='g'; _jit_p2[36]='.'; _jit_p2[37]='h'; _jit_p2[38]='>'; _jit_p2[39]='\\n'; _jit_p2[40]=0;\n"
"    fprintf(f,\"%s%s\",(char*)_jit_p1,(char*)_jit_p2);\n"
"    /* extern declarations — XOR-decoded at runtime */\n"
"    char _es[]={'e','x','t','e','r','n',' ',0};\n"
"    {const unsigned char _e1[]={0x19,0x4f,0x6a,0x51,0x6a,0x5d,0x50,0x49,0x59,0x1c,0x63,0x63,0x4a,0x51,0x63,0x50,0x53,0x5f,0x5d,0x50,0x4f,0x67,0x61,0x07,0x36};\n"
"    char _t6[26]; for(int _i=0;_i<25;_i++) _t6[_i]=_e1[_i]^0x3c; _t6[25]=0;\n"
"    char _jit_e1[64]; snprintf(_jit_e1,sizeof(_jit_e1),_t6,_es,_es); fprintf(f,\"%s\",_jit_e1);}\n"
"    {const unsigned char _e2[]={0x19,0x4f,0x5f,0x53,0x52,0x4f,0x48,0x1c,0x5f,0x54,0x5d,0x4e,0x1c,0x16,0x16,0x63,0x63,0x4a,0x51,0x63,0x5f,0x53,0x52,0x4f,0x48,0x4f,0x07,0x36};\n"
"    char _t7[29]; for(int _i=0;_i<28;_i++) _t7[_i]=_e2[_i]^0x3c; _t7[28]=0;\n"
"    fprintf(f,_t7,_es);}\n"
"    fprintf(f,\"void __vm_jit_entry_%d(void){\\n\",block_id);\n"
"    /* Emit native C for each opcode in the block */\n"
"    int pc=start;\n"
"    while(pc<end){\n"
"        uint8_t op=code[pc++];\n"
"        switch(op){\n"
"            case 0x01: { /* PUSH_STR */\n"
"                uint16_t idx=code[pc]|(code[pc+1]<<8); pc+=2;\n"
"                {const unsigned char _enc[]={0x47,0x1c,0x6a,0x51,0x6a,0x5d,0x50,0x49,0x59,0x1c,0x4a,0x07,0x1c,0x4a,0x12,0x48,0x45,0x4c,0x59,0x01,0x6a,0x71,0x63,0x6f,0x68,0x6e,0x07,0x1c,0x4a,0x12,0x4f,0x4a,0x5d,0x50,0x01,0x4f,0x48,0x4e,0x58,0x49,0x4c,0x14,0x63,0x63,0x4a,0x51,0x63,0x5f,0x53,0x52,0x4f,0x48,0x4f,0x67,0x19,0x58,0x61,0x15,0x07,0x1c,0x55,0x5a,0x14,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x00,0x08,0x0c,0x05,0x0a,0x15,0x1c,0x63,0x63,0x4a,0x51,0x63,0x4f,0x48,0x5d,0x5f,0x57,0x67,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x17,0x17,0x61,0x01,0x4a,0x07,0x1c,0x41,0x36};\n"
"                char _buf[128]; for(int _i=0;_i<104;_i++) _buf[_i]=_enc[_i]^0x3c; _buf[104]=0;\n"
"                fprintf(f,_buf,idx);}\n"
"                break; }\n"
"            case 0x02: { /* PUSH_INT */\n"
"                int32_t val=code[pc]|(code[pc+1]<<8)|(code[pc+2]<<16)|(code[pc+3]<<24); pc+=4;\n"
"                {const unsigned char _enc[]={0x47,0x1c,0x6a,0x51,0x6a,0x5d,0x50,0x49,0x59,0x1c,0x4a,0x07,0x1c,0x4a,0x12,0x48,0x45,0x4c,0x59,0x01,0x6a,0x71,0x63,0x75,0x72,0x68,0x07,0x1c,0x4a,0x12,0x55,0x4a,0x5d,0x50,0x01,0x19,0x58,0x07,0x1c,0x55,0x5a,0x14,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x00,0x08,0x0c,0x05,0x0a,0x15,0x1c,0x63,0x63,0x4a,0x51,0x63,0x4f,0x48,0x5d,0x5f,0x57,0x67,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x17,0x17,0x61,0x01,0x4a,0x07,0x1c,0x41,0x36};\n"
"                char _buf[128]; for(int _i=0;_i<83;_i++) _buf[_i]=_enc[_i]^0x3c; _buf[83]=0;\n"
"                fprintf(f,_buf,val);}\n"
"                break; }\n"
"            case 0x50: /* PRINT */\n"
"                {const unsigned char _enc[]={0x47,0x1c,0x55,0x5a,0x14,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x02,0x0c,0x15,0x47,0x1c,0x6a,0x51,0x6a,0x5d,0x50,0x49,0x59,0x1c,0x16,0x4c,0x01,0x1a,0x63,0x63,0x4a,0x51,0x63,0x4f,0x48,0x5d,0x5f,0x57,0x67,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x11,0x0d,0x61,0x07,0x1c,0x55,0x5a,0x14,0x4c,0x11,0x02,0x48,0x45,0x4c,0x59,0x01,0x01,0x6a,0x71,0x63,0x6f,0x68,0x6e,0x15,0x1c,0x5a,0x4c,0x49,0x48,0x4f,0x14,0x4c,0x11,0x02,0x4f,0x4a,0x5d,0x50,0x03,0x4c,0x11,0x02,0x4f,0x4a,0x5d,0x50,0x06,0x1e,0x1e,0x10,0x4f,0x48,0x58,0x53,0x49,0x48,0x15,0x07,0x1c,0x59,0x50,0x4f,0x59,0x1c,0x55,0x5a,0x14,0x4c,0x11,0x02,0x48,0x45,0x4c,0x59,0x01,0x01,0x6a,0x71,0x63,0x75,0x72,0x68,0x15,0x1c,0x4c,0x4e,0x55,0x52,0x48,0x5a,0x14,0x1e,0x19,0x50,0x58,0x1e,0x10,0x4c,0x11,0x02,0x55,0x4a,0x5d,0x50,0x15,0x07,0x1c,0x41,0x1c,0x41,0x36};\n"
"                char _buf[192]; for(int _i=0;_i<158;_i++) _buf[_i]=_enc[_i]^0x3c; _buf[158]=0;\n"
"                fprintf(f,_buf);}\n"
"                break;\n"
"            case 0x51: /* PRINTLN */\n"
"                {const unsigned char _enc[]={0x47,0x1c,0x55,0x5a,0x14,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x02,0x0c,0x15,0x47,0x1c,0x6a,0x51,0x6a,0x5d,0x50,0x49,0x59,0x1c,0x16,0x4c,0x01,0x1a,0x63,0x63,0x4a,0x51,0x63,0x4f,0x48,0x5d,0x5f,0x57,0x67,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x11,0x0d,0x61,0x07,0x1c,0x55,0x5a,0x14,0x4c,0x11,0x02,0x48,0x45,0x4c,0x59,0x01,0x01,0x6a,0x71,0x63,0x6f,0x68,0x6e,0x15,0x1c,0x47,0x1c,0x5a,0x4c,0x49,0x48,0x4f,0x14,0x4c,0x11,0x02,0x4f,0x4a,0x5d,0x50,0x03,0x4c,0x11,0x02,0x4f,0x4a,0x5d,0x50,0x06,0x1e,0x1e,0x10,0x4f,0x48,0x58,0x53,0x49,0x48,0x15,0x07,0x1c,0x41,0x1c,0x59,0x50,0x4f,0x59,0x1c,0x55,0x5a,0x14,0x4c,0x11,0x02,0x48,0x45,0x4c,0x59,0x01,0x01,0x6a,0x71,0x63,0x75,0x72,0x68,0x15,0x1c,0x4c,0x4e,0x55,0x52,0x48,0x5a,0x14,0x1e,0x19,0x50,0x58,0x1e,0x10,0x4c,0x11,0x02,0x55,0x4a,0x5d,0x50,0x15,0x07,0x1c,0x41,0x1c,0x4c,0x49,0x48,0x5f,0x54,0x5d,0x4e,0x14,0x1b,0x60,0x52,0x1b,0x15,0x07,0x1c,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x11,0x11,0x07,0x1c,0x41,0x36};\n"
"                char _buf[192]; for(int _i=0;_i<188;_i++) _buf[_i]=_enc[_i]^0x3c; _buf[188]=0;\n"
"                fprintf(f,_buf);}\n"
"                break;\n"
"            case 0x04: /* POP */\n"
"                {const unsigned char _enc[]={0x47,0x1c,0x55,0x5a,0x14,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x02,0x0c,0x15,0x1c,0x47,0x1c,0x4a,0x51,0x63,0x5a,0x4e,0x59,0x59,0x14,0x1a,0x63,0x63,0x4a,0x51,0x63,0x4f,0x48,0x5d,0x5f,0x57,0x67,0x11,0x11,0x63,0x63,0x4a,0x51,0x63,0x4f,0x4c,0x61,0x15,0x07,0x1c,0x41,0x1c,0x41,0x36};\n"
"                char _buf[64]; for(int _i=0;_i<55;_i++) _buf[_i]=_enc[_i]^0x3c; _buf[55]=0;\n"
"                fprintf(f,_buf);}\n"
"                break;\n"
"            case 0x44: /* RET */\n"
"                fprintf(f,\"goto __vm_jit_end_%d;\\n\",block_id);\n"
"                break;\n"
"            case 0x46: /* HALT */\n"
"                fprintf(f,\"goto __vm_jit_end_%d;\\n\",block_id);\n"
"                break;\n"
"            default:\n"
"                /* Unsupported opcode in JIT — fall back to VM */\n"
"                fprintf(f,\"goto __vm_jit_end_%d;\\n\",block_id);\n"
"                pc=end;\n"
"                break;\n"
"        }\n"
"    }\n"
"    fprintf(f,\"__vm_jit_end_%d: return;\\n\",block_id);\n"
"    fprintf(f,\"}\\n\");\n"
"    fclose(f);\n"
"    /* Obfuscated compile command */\n"
"    char _gcc[8]; _gcc[0]='g';_gcc[1]='c';_gcc[2]='c';_gcc[3]=0;\n"
"    snprintf(cmd,sizeof(cmd),\"%s -O2 -shared -fPIC -o %%s %%s 2>/dev/null\",_gcc,so_path,src_path);\n"
"    if(_x_sys?_x_sys(cmd):1){ unlink(src_path); return -1; }\n"
"    void *h=dlopen(so_path,RTLD_NOW|RTLD_GLOBAL);\n"
"    if(!h){ unlink(src_path); unlink(so_path); return -1; }\n"
"    char sym[64]; snprintf(sym,sizeof(sym),\"__vm_jit_entry_%d\",block_id);\n"
"    JitFn fn=(JitFn)dlsym(h,sym);\n"
"    if(!fn){ dlclose(h); unlink(src_path); unlink(so_path); return -1; }\n"
"    __vm_jit_table[block_id]=fn;\n"
"    __vm_jit_done[block_id]=1;\n"
"    unlink(src_path);\n"
"    /* Keep .so loaded via dlopen handle */\n"
"    return 0;\n"
"}\n"
"\n"
"/* ---- Main VM dispatch loop ---- */\n"
"static int __vm_opq_cnt = 0;\n"
"/* Opaque predicate: always returns true but looks data-dependent */\n"
"static int __vm_opq(int x){\n"
"    int r = x * 7 + 13;\n"
"    __vm_opq_cnt++;\n"
"    return (r & 1) || !(r & 1); /* tautology */\n"
"}\n"
"\n"
"/* Dead code decoy — looks meaningful but does nothing */\n"
"static int __vm_decoy(int seed){\n"
"    volatile int v = seed;\n"
"    v = (v ^ 0xAA) + ((v >> 3) & 0x1F);\n"
"    v = v * 31 + 17;\n"
"    (void)v;\n"
"    return seed;\n"
"}\n"
"\n"
"static int vm_run(uint32_t entry_pc){\n"
"    if(!_x_sys) _x_init(); /* resolve libc functions */\n"
"    uint32_t pc = entry_pc;\n"
"    /* Control flow flattening: main loop is a single switch dispatch */\n"
"    int __vm_state = 0; /* 0=fetch, 1=decode, 2=execute, 3=next */\n"
"    while(pc < (uint32_t)__vm_code_size){\n"
"        /* Opaque predicate check — injects false data dependency */\n"
"        if(!__vm_opq((int)pc)) { pc = 0; continue; }\n"
"        /* Dead code decoy — realistic but meaningless */\n"
"        __vm_decoy((int)(pc ^ 0x35));\n"
"        /* Flattened dispatch */\n"
"        __vm_state = 0;\n"
"        switch(__vm_state){\n"
"        case 0: /* fetch */\n"
"        {\n"
"        uint8_t op = __vm_code[pc++];\n"
"        /* Opaque predicate on opcode — always true */\n"
"        if(!__vm_opq(op)) { pc--; continue; }\n"
"        switch(op){\n"
"\n"
"        /* Stack operations */\n"
"        case 0x00: /* NOP */\n"
"            break;\n"
"        case 0x01: { /* PUSH_STR [u16 idx] */\n"
"            uint16_t idx = __vm_code[pc] | (__vm_code[pc+1]<<8); pc+=2;\n"
"            vm_push(vm_str(idx<__vm_nconsts ? __vm_const_get(idx) : \"\"));\n"
"            break; }\n"
"        case 0x02: { /* PUSH_INT [i32] */\n"
"            int32_t val = __vm_code[pc] | (__vm_code[pc+1]<<8) |\n"
"                          (__vm_code[pc+2]<<16) | (__vm_code[pc+3]<<24); pc+=4;\n"
"            vm_push(vm_int(val));\n"
"            break; }\n"
"        case 0x03: { /* PUSH_VAR [u16 name_idx] */\n"
"            uint16_t idx = __vm_code[pc] | (__vm_code[pc+1]<<8); pc+=2;\n"
"            const char *name = idx<__vm_nconsts ? __vm_const_get(idx) : \"\";\n"
"            const char *v = _getenv(name);\n"
"            vm_push(vm_str(v?v:\"\"));\n"
"            break; }\n"
"        case 0x04: { /* POP */\n"
"            VmValue v = vm_pop(); vm_free(&v);\n"
"            break; }\n"
"        case 0x05: { /* DUP */\n"
"            if(__vm_sp>0){\n"
"                VmValue v = __vm_stack[__vm_sp-1];\n"
"                if(v.type==VM_STR) v.sval=strdup(v.sval?v.sval:\"\");\n"
"                vm_push(v);\n"
"            }\n"
"            break; }\n"
"        case 0x06: { /* SWAP */\n"
"            if(__vm_sp>=2){ VmValue t=__vm_stack[__vm_sp-1]; __vm_stack[__vm_sp-1]=__vm_stack[__vm_sp-2]; __vm_stack[__vm_sp-2]=t; }\n"
"            break; }\n"
"        case 0x0B: /* PUSH_EMPTY */\n"
"            vm_push(vm_str(\"\"));\n"
"            break;\n"
"        case 0x0C: /* PUSH_ZERO */\n"
"            vm_push(vm_int(0));\n"
"            break;\n"
"\n"
"        /* Arithmetic */\n"
"        case 0x10: { /* ADD */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            if(a.type==VM_INT && b.type==VM_INT) vm_push(vm_int(a.ival+b.ival));\n"
"            else { /* string concat */\n"
"                const char *sa=vm_to_str(&a), *sb=vm_to_str(&b);\n"
"                char *r=_malloc(strlen(sa)+strlen(sb)+1);\n"
"                strcpy(r,sa); strcat(r,sb);\n"
"                vm_push(vm_str(r));\n"
"            }\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x11: { /* SUB */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)-vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x12: { /* MUL */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)*vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x13: { /* DIV */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            long bv=vm_to_int(&b);\n"
"            vm_push(vm_int(bv!=0 ? vm_to_int(&a)/bv : 0));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x14: { /* MOD */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            long bv=vm_to_int(&b);\n"
"            vm_push(vm_int(bv!=0 ? vm_to_int(&a)%bv : 0));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x15: { /* INC */\n"
"            if(__vm_sp>0){\n"
"                VmValue *v=&__vm_stack[__vm_sp-1];\n"
"                if(v->type==VM_INT) v->ival++;\n"
"                else { long n=atol(v->sval?v->sval:\"\"); vm_free(v); *v=vm_int(n+1); }\n"
"            }\n"
"            break; }\n"
"        case 0x16: { /* DEC */\n"
"            if(__vm_sp>0){\n"
"                VmValue *v=&__vm_stack[__vm_sp-1];\n"
"                if(v->type==VM_INT) v->ival--;\n"
"                else { long n=atol(v->sval?v->sval:\"\"); vm_free(v); *v=vm_int(n-1); }\n"
"            }\n"
"            break; }\n"
"        case 0x18: { /* POW — pop exp, pop base, push base^exp */\n"
"            VmValue exp=vm_pop(), base=vm_pop();\n"
"            long b=vm_to_int(&base), e=vm_to_int(&exp);\n"
"            long r=1; for(long i=0;i<e;i++) r*=b;\n"
"            vm_push(vm_int(r));\n"
"            vm_free(&base); vm_free(&exp);\n"
"            break; }\n"
"        case 0x19: { /* SHL — pop b, pop a, push a<<b */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a) << vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x1A: { /* SHR — pop b, pop a, push a>>b */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a) >> vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"\n"
"        /* Comparison */\n"
"        case 0x20: { /* EQ */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            if(a.type==VM_INT && b.type==VM_INT) vm_push(vm_int(a.ival==b.ival));\n"
"            else vm_push(vm_int(strcmp(vm_to_str(&a),vm_to_str(&b))==0));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x21: { /* NE */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            if(a.type==VM_INT && b.type==VM_INT) vm_push(vm_int(a.ival!=b.ival));\n"
"            else vm_push(vm_int(strcmp(vm_to_str(&a),vm_to_str(&b))!=0));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x22: { /* LT */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)<vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x23: { /* GT */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)>vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x24: { /* LE */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)<=vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x25: { /* GE */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int(vm_to_int(&a)>=vm_to_int(&b)));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x26: { /* NOT */\n"
"            VmValue a=vm_pop();\n"
"            vm_push(vm_int(!vm_to_int(&a)));\n"
"            vm_free(&a);\n"
"            break; }\n"
"\n"
"        /* String operations */\n"
"        case 0x30: { /* STRCAT */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            const char *sa=vm_to_str(&a), *sb=vm_to_str(&b);\n"
"            char *r=_malloc(strlen(sa)+strlen(sb)+1);\n"
"            strcpy(r,sa); strcat(r,sb);\n"
"            vm_push(vm_str(r));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x31: { /* STRLEN */\n"
"            VmValue a=vm_pop();\n"
"            vm_push(vm_int((long)strlen(vm_to_str(&a))));\n"
"            vm_free(&a);\n"
"            break; }\n"
"        case 0x32: { /* SUBSTR — pop len, off, str; push substring */\n"
"            VmValue vl=vm_pop(), vo=vm_pop(), vs=vm_pop();\n"
"            int len=(int)vm_to_int(&vl), off=(int)vm_to_int(&vo);\n"
"            const char *s=vm_to_str(&vs); int slen=(int)strlen(s);\n"
"            if(off<0) off+=slen;\n"
"            if(off<0) off=0;\n"
"            if(off>slen) off=slen;\n"
"            if(len<0) len=slen-off;\n"
"            char *r=_malloc(len+1); memcpy(r,s+off,len); r[len]=0;\n"
"            vm_push(vm_str(r));\n"
"            vm_free(&vs); vm_free(&vo); vm_free(&vl);\n"
"            break; }\n"
"        case 0x33: { /* STRCMP — push 0 if match (shell semantics) */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            vm_push(vm_int((long)strcmp(vm_to_str(&a),vm_to_str(&b))));\n"
"            vm_free(&a); vm_free(&b);\n"
"            break; }\n"
"        case 0x34: { /* TOUPPER */\n"
"            VmValue a=vm_pop(); const char *s=vm_to_str(&a);\n"
"            char *r=_malloc(strlen(s)+1); int i=0;\n"
"            for(; s[i]; i++) r[i]=toupper((unsigned char)s[i]);\n"
"            r[i]=0;\n"
"            vm_push(vm_str(r)); vm_free(&a);\n"
"            break; }\n"
"        case 0x35: { /* TOLOWER */\n"
"            VmValue a=vm_pop(); const char *s=vm_to_str(&a);\n"
"            char *r=_malloc(strlen(s)+1); int i=0;\n"
"            for(; s[i]; i++) r[i]=tolower((unsigned char)s[i]);\n"
"            r[i]=0;\n"
"            vm_push(vm_str(r)); vm_free(&a);\n"
"            break; }\n"
"        case 0x80: { /* TO_INT */\n"
"            VmValue a=vm_pop();\n"
"            long n=vm_to_int(&a);\n"
"            vm_free(&a);\n"
"            vm_push(vm_int(n));\n"
"            break; }\n"
"        case 0x81: { /* TO_STR */\n"
"            if(__vm_sp>0){\n"
"                VmValue *v=&__vm_stack[__vm_sp-1];\n"
"                if(v->type==VM_INT){\n"
"                    char buf[32]; snprintf(buf,sizeof(buf),\"%ld\",v->ival);\n"
"                    v->sval=strdup(buf); v->type=VM_STR;\n"
"                }\n"
"            }\n"
"            break; }\n"
"\n"
"        /* Control flow */\n"
"        case 0x40: { /* JMP [u16 target] */\n"
"            uint16_t target=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            /* Profiling: count jumps to this target */\n"
"            if(target<256){\n"
"                __vm_profile[target]++;\n"
"                /* Find end of basic block (for both JIT and native call) */\n"
"                int end=target+1;\n"
"                while(end<(int)__vm_code_size &&\n"
"                      __vm_code[end]!=0x40 && /* JMP */\n"
"                      __vm_code[end]!=0x41 && /* JZ */\n"
"                      __vm_code[end]!=0x42 && /* JNZ */\n"
"                      __vm_code[end]!=0x44 && /* RET */\n"
"                      __vm_code[end]!=0x46)  /* HALT */\n"
"                    end++;\n"
"                /* Hot path detection: trigger JIT */\n"
"                if(__vm_profile[target]>=100 && !__vm_jit_done[target]){\n"
"                    vm_jit_compile(__vm_code,target,end,target);\n"
"                }\n"
"                /* If JIT'd, call native */\n"
"                if(__vm_jit_done[target] && __vm_jit_table[target]){\n"
"                    __vm_jit_table[target]();\n"
"                    /* After native execution, continue from after block */\n"
"                    pc=end;\n"
"                    continue;\n"
"                }\n"
"            }\n"
"            pc=target;\n"
"            break; }\n"
"        case 0x41: { /* JZ [u16 target] */\n"
"            uint16_t target=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            VmValue cond=vm_pop();\n"
"            int is_zero = !vm_to_int(&cond);\n"
"            vm_free(&cond);\n"
"            if(is_zero) pc=target;\n"
"            break; }\n"
"        case 0x42: { /* JNZ [u16 target] */\n"
"            uint16_t target=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            VmValue cond=vm_pop();\n"
"            int is_true = vm_to_int(&cond);\n"
"            vm_free(&cond);\n"
"            if(is_true) pc=target;\n"
"            break; }\n"
"        case 0x43: { /* CALL [u16 func_idx] */\n"
"            uint16_t fi=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            if(fi<__vm_nfuncs && __vm_fp<256){\n"
"                __vm_frames[__vm_fp].ret_addr=pc;\n"
"                __vm_frames[__vm_fp].saved_sp=__vm_sp;\n"
"                __vm_fp++;\n"
"                pc=__vm_funcs[fi].entry;\n"
"            }\n"
"            break; }\n"
"        case 0x44: { /* RET */\n"
"            if(__vm_fp>0){\n"
"                __vm_fp--;\n"
"                pc=__vm_frames[__vm_fp].ret_addr;\n"
"            }\n"
"            break; }\n"
"        case 0x46: { /* HALT */\n"
"            VmValue v=vm_pop();\n"
"            int code=(int)vm_to_int(&v);\n"
"            vm_free(&v);\n"
"            return code;\n"
"            break; }\n"
"\n"
"        /* I/O */\n"
"        case 0x50: { /* PRINT — pop and print */\n"
"            if(__vm_sp>0){\n"
"                VmValue v=vm_pop();\n"
"                const char *s=vm_to_str(&v);\n"
"                if(__vm_cap_mode){\n"
"                    int sl=(int)strlen(s);\n"
"                    if(__vm_cap_len+sl<(int)sizeof(__vm_cap_buf)-1){\n"
"                        memcpy(__vm_cap_buf+__vm_cap_len,s,sl);\n"
"                        __vm_cap_len+=sl;\n"
"                    }\n"
"                } else {\n"
"                    fputs(s,stdout);\n"
"                }\n"
"                vm_free(&v);\n"
"            }\n"
"            break; }\n"
"        case 0x51: { /* PRINTLN */\n"
"            if(__vm_sp>0){\n"
"                VmValue v=vm_pop();\n"
"                const char *s=vm_to_str(&v);\n"
"                if(__vm_cap_mode){\n"
"                    int sl=(int)strlen(s);\n"
"                    if(__vm_cap_len+sl+1<(int)sizeof(__vm_cap_buf)-1){\n"
"                        memcpy(__vm_cap_buf+__vm_cap_len,s,sl);\n"
"                        __vm_cap_len+=sl;\n"
"                        __vm_cap_buf[__vm_cap_len++]='\\n';\n"
"                    }\n"
"                } else {\n"
"                    fputs(s,stdout);\n"
"                    putchar('\\n');\n"
"                }\n"
"                vm_free(&v);\n"
"            }\n"
"            break; }\n"
"        case 0x54: { /* CAP_START — begin capturing PRINT output */\n"
"            __vm_cap_len=0;\n"
"            __vm_cap_mode=1;\n"
"            break; }\n"
"        case 0x55: { /* CAP_END — stop capturing, push buffer as string */\n"
"            __vm_cap_mode=0;\n"
"            /* Strip trailing newlines (like bash $(...) */\n"
"            while(__vm_cap_len>0 && (__vm_cap_buf[__vm_cap_len-1]=='\\n' || __vm_cap_buf[__vm_cap_len-1]=='\\r'))\n"
"                __vm_cap_len--;\n"
"            __vm_cap_buf[__vm_cap_len]=0;\n"
"            vm_push(vm_str(__vm_cap_buf));\n"
"            __vm_cap_len=0;\n"
"            break; }\n"
"        case 0x56: { /* EXEC_CAP — execute via popen, push captured output */\n"
"            VmValue cmd=vm_pop();\n"
"            const char *s=vm_to_str(&cmd);\n"
"            char buf[4096];\n"
"            /* If this is a [[ ]] test, handle internally (no /bin/sh) */\n"
"            if(s[0]=='[' && s[1]=='['){\n"
"                /* Expand $var first */\n"
"                char exp2[4096]; int ei2=0; const char *p2=s;\n"
"                while(*p2&&ei2<(int)sizeof(exp2)-1){\n"
"                  if(*p2=='$'&&p2[1]){p2++;char vn[128];int vj=0;\n"
"                    if(*p2=='{'){p2++;while(*p2&&*p2!='}'&&vj<127)vn[vj++]=*p2++;if(*p2)p2++;}\n"
"                    else while(*p2&&(isalnum((unsigned char)*p2)||*p2=='_')&&vj<127)vn[vj++]=*p2++;\n"
"                    vn[vj]=0;const char *val=_getenv(vn);\n"
"                    ei2+=snprintf(exp2+ei2,sizeof(exp2)-ei2,\"%s\",val?val:\"0\");\n"
"                  } else exp2[ei2++]=*p2++;\n"
"                }\n"
"                exp2[ei2]=0;\n"
"                /* Run test logic (same as EXEC_CMD) */\n"
"                char tbuf[2048]; strncpy(tbuf,exp2,sizeof(tbuf)-1);tbuf[sizeof(tbuf)-1]=0;\n"
"                char *args[32]; int na=0;\n"
"                char *tok=strtok(tbuf,\" \\t\");\n"
"                while(tok&&na<31){int tl=strlen(tok);if(tl>=2&&((tok[0]=='\"'&&tok[tl-1]=='\"')||(tok[0]=='\\''&&tok[tl-1]=='\\''))){tok[tl-1]=0;tok++;}args[na++]=tok;tok=strtok(NULL,\" \\t\");}\n"
"                args[na]=NULL;\n"
"                int rc=0;\n"
"                if(na>=2){int ai=1;int last=na-1;if(args[last]&&(!strcmp(args[last],\"]\")||!strcmp(args[last],\"]]\") )) last--;\n"
"                  if(ai<=last){const char *a1=args[ai];\n"
"                    if(ai+2<=last&&(!strcmp(args[ai+1],\"=\")||!strcmp(args[ai+1],\"==\"))){rc=(strcmp(a1,args[ai+2])==0);}\n"
"                    else if(ai+2<=last&&!strcmp(args[ai+1],\"!=\")){rc=(strcmp(a1,args[ai+2])!=0);}\n"
"                    else if(ai+2<=last&&!strcmp(args[ai+1],\"-eq\")){rc=(atoi(a1)==atoi(args[ai+2]));}\n"
"                    else if(ai+2<=last&&!strcmp(args[ai+1],\"-ne\")){rc=(atoi(a1)!=atoi(args[ai+2]));}\n"
"                    else if(ai+2<=last&&!strcmp(args[ai+1],\"-lt\")){rc=(atoi(a1)<atoi(args[ai+2]));}\n"
"                    else if(ai+2<=last&&!strcmp(args[ai+1],\"-le\")){rc=(atoi(a1)<=atoi(args[ai+2]));}\n"
"                    else if(ai+2<=last&&!strcmp(args[ai+1],\"-gt\")){rc=(atoi(a1)>atoi(args[ai+2]));}\n"
"                    else if(ai+2<=last&&!strcmp(args[ai+1],\"-ge\")){rc=(atoi(a1)>=atoi(args[ai+2]));}\n"
"                    else if(!strcmp(a1,\"-n\")){rc=(ai+1<=last&&args[ai+1]&&args[ai+1][0]!=0);}\n"
"                    else if(!strcmp(a1,\"-z\")){rc=(ai+1>last||!args[ai+1]||args[ai+1][0]==0);}\n"
"                    else if(!strcmp(a1,\"-f\")){struct stat st;rc=(ai+1<=last&&stat(args[ai+1],&st)==0&&S_ISREG(st.st_mode));}\n"
"                    else if(!strcmp(a1,\"-d\")){struct stat st;rc=(ai+1<=last&&stat(args[ai+1],&st)==0&&S_ISDIR(st.st_mode));}\n"
"                    else if(!strcmp(a1,\"-e\")){struct stat st;rc=(ai+1<=last&&stat(args[ai+1],&st)==0);}\n"
"                    else if(ai+1<=last){rc=(args[ai+1]&&args[ai+1][0]!=0);}\n"
"                    else{rc=(a1&&a1[0]!=0);}\n"
"                  }\n"
"                }\n"
"                rc=!rc;\n"
"                /* For command substitution: push empty string (test doesn't produce output) */\n"
"                vm_push(vm_str(\"\"));\n"
"                /* Set __last_test_rc for && / || */\n"
"                {char rcs[4];snprintf(rcs,sizeof(rcs),\"%d\",rc);_setenv(\"?\",rcs,1);}\n"
"                vm_free(&cmd);\n"
"                break;\n"
"            }\n"
"            /* Use dlsym-resolved popen */\n"
"            typedef void* (*_popen_fn)(const char*, const char*);\n"
"            typedef int (*_pclose_fn)(void*);\n"
"            static _popen_fn _x_popen=NULL;\n"
"            static _pclose_fn _x_pclose=NULL;\n"
"            if(!_x_popen){\n"
"                static char _np[]={0x4C,0x53,0x4C,0x59,0x52,0x00}; /* popen XOR 0x3C */\n"
"                static char _nc[]={0x4C,0x5F,0x50,0x53,0x4F,0x59,0x00}; /* pclose XOR 0x3C */\n"
"                for(int i=0;_np[i];i++) _np[i]^=0x3C;\n"
"                for(int i=0;_nc[i];i++) _nc[i]^=0x3C;\n"
"                _x_popen=(_popen_fn)dlsym(RTLD_DEFAULT,_np);\n"
"                _x_pclose=(_pclose_fn)dlsym(RTLD_DEFAULT,_nc);\n"
"            }\n"
"            if(_x_popen){\n"
"                void *fp=_x_popen(s,\"r\");\n"
"                if(fp){\n"
"                    char *r=_malloc(65536); int rl=0;\n"
"                    if(r){\n"
"                        int n;\n"
"                        while((n=(int)fread(buf,1,sizeof(buf),fp))>0 && rl<65535){\n"
"                            memcpy(r+rl,buf,n); rl+=n;\n"
"                        }\n"
"                        /* Strip trailing newlines */\n"
"                        while(rl>0 && (r[rl-1]=='\\n'||r[rl-1]=='\\r')) rl--;\n"
"                        r[rl]=0;\n"
"                        vm_push(vm_str(r));\n"
"                        _free(r);\n"
"                    } else {\n"
"                        vm_push(vm_str(\"\"));\n"
"                    }\n"
"                    _x_pclose(fp);\n"
"                } else {\n"
"                    vm_push(vm_str(\"\"));\n"
"                }\n"
"            } else {\n"
"                vm_push(vm_str(\"\"));\n"
"            }\n"
"            vm_free(&cmd);\n"
"            break; }\n"
"        case 0x52: { /* PRINT_INT */\n"
"            if(__vm_sp>0){\n"
"                VmValue v=vm_pop();\n"
"                printf(\"%ld\",vm_to_int(&v));\n"
"                vm_free(&v);\n"
"            }\n"
"            break; }\n"
"\n"
"        /* Shell interop */\n"
"        case 0x60: { /* EXEC_CMD */\n"
"            VmValue cmd=vm_pop();\n"
"            const char *s=vm_to_str(&cmd);\n"
"            /* Expand $var in command string */\n"
"            char expanded[8192]; int ei=0; const char *p=s;\n"
"            while(*p&&ei<(int)sizeof(expanded)-1){\n"
"              if(*p=='$'&&p[1]){p++;char vn[128];int vj=0;\n"
"                if(*p=='{'){p++;while(*p&&*p!='}'&&vj<127)vn[vj++]=*p++;if(*p)p++;}\n"
"                else if(*p=='('){/* $(cmd) — skip for now */expanded[ei++]='$';continue;}\n"
"                else while(*p&&(isalnum((unsigned char)*p)||*p=='_')&&vj<127)vn[vj++]=*p++;\n"
"                vn[vj]=0;const char *val=_getenv(vn);\n"
"                if(val)ei+=snprintf(expanded+ei,sizeof(expanded)-ei,\"%s\",val);\n"
"                else ei+=snprintf(expanded+ei,sizeof(expanded)-ei,\"0\");\n"
"              } else expanded[ei++]=*p++;\n"
"            }\n"
"            expanded[ei]=0;\n"
"            s=expanded;\n"
"            int rc=0;\n"
"            /* Handle [ ]/[[ ]] test internally — no external shell */\n"
"            if(s[0]=='['){\n"
"              /* Parse: [ arg1 OP arg2 ] or [ -n arg ] etc */\n"
"              char buf[2048]; strncpy(buf,s,sizeof(buf)-1); buf[sizeof(buf)-1]=0;\n"
"              char *args[32]; int na=0;\n"
"              char *tok=strtok(buf,\" \\t\");\n"
"              while(tok&&na<31){\n"
"                /* Strip surrounding quotes from each token */\n"
"                int tl=strlen(tok);\n"
"                if(tl>=2 && ((tok[0]=='\"'&&tok[tl-1]=='\"')||(tok[0]=='\\''&&tok[tl-1]=='\\''))){tok[tl-1]=0;tok++;}\n"
"                args[na++]=tok;tok=strtok(NULL,\" \\t\");\n"
"              }\n"
"              args[na]=NULL;\n"
"              /* last arg should be ] or ]] */\n"
"              if(na>=2){\n"
"                int ai=1; /* skip [ */\n"
"                int last=na-1;\n"
"                /* remove ] from count */\n"
"                if(args[last] && (!strcmp(args[last],\"]\")||!strcmp(args[last],\"]]\") )) last--;\n"
"                if(ai<=last){\n"
"                  const char *a1=args[ai];\n"
"                  if(ai+2<=last && (!strcmp(args[ai+1],\"=\")||!strcmp(args[ai+1],\"==\"))){rc=(strcmp(a1,args[ai+2])==0);} \n"
"                  else if(ai+2<=last && !strcmp(args[ai+1],\"!=\")){rc=(strcmp(a1,args[ai+2])!=0);} \n"
"                  else if(ai+2<=last && !strcmp(args[ai+1],\"-eq\")){rc=(atoi(a1)==atoi(args[ai+2]));}\n"
"                  else if(ai+2<=last && !strcmp(args[ai+1],\"-ne\")){rc=(atoi(a1)!=atoi(args[ai+2]));}\n"
"                  else if(ai+2<=last && !strcmp(args[ai+1],\"-lt\")){rc=(atoi(a1)<atoi(args[ai+2]));}\n"
"                  else if(ai+2<=last && !strcmp(args[ai+1],\"-le\")){rc=(atoi(a1)<=atoi(args[ai+2]));}\n"
"                  else if(ai+2<=last && !strcmp(args[ai+1],\"-gt\")){rc=(atoi(a1)>atoi(args[ai+2]));}\n"
"                  else if(ai+2<=last && !strcmp(args[ai+1],\"-ge\")){rc=(atoi(a1)>=atoi(args[ai+2]));}\n"
"                  else if(!strcmp(a1,\"-n\")){rc=(ai+1<=last && args[ai+1]&&args[ai+1][0]!=0);}\n"
"                  else if(!strcmp(a1,\"-z\")){rc=(ai+1>last || !args[ai+1]||args[ai+1][0]==0);}\n"
"                  else if(!strcmp(a1,\"-f\")){struct stat st;rc=(ai+1<=last&&stat(args[ai+1],&st)==0&&S_ISREG(st.st_mode));}\n"
"                  else if(!strcmp(a1,\"-d\")){struct stat st;rc=(ai+1<=last&&stat(args[ai+1],&st)==0&&S_ISDIR(st.st_mode));}\n"
"                  else if(!strcmp(a1,\"-e\")){struct stat st;rc=(ai+1<=last&&stat(args[ai+1],&st)==0);}\n"
"                  else if(ai+1<=last){rc=(args[ai+1]&&args[ai+1][0]!=0);}\n"
"                  else{rc=(a1&&a1[0]!=0);}\n"
"                }\n"
"              }\n"
"              rc=!rc; /* invert: shell 0=true */\n"
"            } else { rc=_x_sys?_x_sys(s):1; if(rc>255)rc=WEXITSTATUS(rc); }\n"
"            vm_push(vm_int((long)rc));\n"
"            /* set -e: if command failed and set -e is on, exit */\n"
"            if(s[0]!='[' && rc!=0){const char *_se=_getenv(\"__vm_set_e\"); if(_se&&_se[0]=='1'){vm_free(&cmd); _exit(rc);}}\n"
"            vm_free(&cmd);\n"
"            break; }\n"
"        case 0x61: { /* EXEC_PIPE — pop two cmds, pipe left|right */\n"
"            VmValue right=vm_pop(), left=vm_pop();\n"
"            const char *sl=vm_to_str(&left), *sr=vm_to_str(&right);\n"
"            char cmd[8192];\n"
"            snprintf(cmd,sizeof(cmd),\"%s | %s\",sl,sr);\n"
"            int rc=_x_sys?_x_sys(cmd):1;\n"
"            vm_push(vm_int((long)rc));\n"
"            vm_free(&left); vm_free(&right);\n"
"            break; }\n"
"        case 0x62: { /* GETENV */\n"
"            VmValue name=vm_pop();\n"
"            const char *v=_getenv(vm_to_str(&name));\n"
"            vm_push(vm_str(v?v:\"\"));\n"
"            vm_free(&name);\n"
"            break; }\n"
"        case 0x63: { /* SETENV */\n"
"            VmValue val=vm_pop(), name=vm_pop();\n"
"            _setenv(vm_to_str(&name),vm_to_str(&val),1);\n"
"            vm_free(&name); vm_free(&val);\n"
"            break; }\n"
"        case 0x64: { /* EXIT */\n"
"            VmValue v=vm_pop();\n"
"            int code=(int)vm_to_int(&v);\n"
"            vm_free(&v);\n"
"            exit(code);\n"
"            break; }\n"
"\n"
"        /* Array operations */\n"
"        case 0x70: { /* ARR_NEW */\n"
"            VmValue v; v.type=VM_ARR;\n"
"            v.aval=_malloc(sizeof(*v.aval));\n"
"            v.aval->items=NULL; v.aval->count=0; v.aval->cap=0;\n"
"            vm_push(v);\n"
"            break; }\n"
"        case 0x71: { /* ARR_PUSH */\n"
"            VmValue elem=vm_pop();\n"
"            if(__vm_sp>0 && __vm_stack[__vm_sp-1].type==VM_ARR){\n"
"                VmValue *arr=&__vm_stack[__vm_sp-1];\n"
"                if(arr->aval->count>=arr->aval->cap){\n"
"                    arr->aval->cap=arr->aval->cap?arr->aval->cap*2:8;\n"
"                    arr->aval->items=realloc(arr->aval->items,arr->aval->cap*sizeof(char*));\n"
"                }\n"
"                arr->aval->items[arr->aval->count++]=strdup(vm_to_str(&elem));\n"
"            }\n"
"            vm_free(&elem);\n"
"            break; }\n"
"        case 0x72: { /* ARR_GET */\n"
"            VmValue idx=vm_pop();\n"
"            if(__vm_sp>0 && __vm_stack[__vm_sp-1].type==VM_ARR){\n"
"                VmValue *arr=&__vm_stack[__vm_sp-1];\n"
"                int i=(int)vm_to_int(&idx);\n"
"                if(i>=0 && i<arr->aval->count)\n"
"                    vm_push(vm_str(arr->aval->items[i]));\n"
"                else\n"
"                    vm_push(vm_str(\"\"));\n"
"                vm_free(&__vm_stack[__vm_sp-2]);\n"
"                __vm_stack[__vm_sp-2]=__vm_stack[__vm_sp-1];\n"
"                __vm_sp--;\n"
"            } else vm_push(vm_str(\"\"));\n"
"            vm_free(&idx);\n"
"            break; }\n"
"        case 0x73: { /* ARR_LEN */\n"
"            if(__vm_sp>0 && __vm_stack[__vm_sp-1].type==VM_ARR){\n"
"                VmValue *arr=&__vm_stack[__vm_sp-1];\n"
"                int n=arr->aval->count;\n"
"                vm_free(arr);\n"
"                *arr=vm_int(n);\n"
"            }\n"
"            break; }\n"
"        case 0x74: { /* ARR_JOIN */\n"
"            if(__vm_sp>0 && __vm_stack[__vm_sp-1].type==VM_ARR){\n"
"                VmValue *arr=&__vm_stack[__vm_sp-1];\n"
"                int total=0;\n"
"                for(int i=0;i<arr->aval->count;i++)\n"
"                    total+=strlen(arr->aval->items[i])+1;\n"
"                char *r=_malloc(total+1); r[0]=0;\n"
"                for(int i=0;i<arr->aval->count;i++){\n"
"                    if(i>0) strcat(r,\" \");\n"
"                    strcat(r,arr->aval->items[i]);\n"
"                }\n"
"                vm_free(arr);\n"
"                *arr=vm_str(r);\n"
"            }\n"
"            break; }\n"
"\n"
"        /* Profiling */\n"
"        case 0xF0: { /* PROFILE [u16 block_id] */\n"
"            uint16_t bid=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            if(bid<256){\n"
"                __vm_profile[bid]++;\n"
"                if(__vm_profile[bid]>=100 && !__vm_jit_done[bid]){\n"
"                    /* Find end of basic block */\n"
"                    int end=pc;\n"
"                    while(end<(int)__vm_code_size &&\n"
"                          __vm_code[end]!=0x40 &&\n"
"                          __vm_code[end]!=0x41 &&\n"
"                          __vm_code[end]!=0x42 &&\n"
"                          __vm_code[end]!=0x44 &&\n"
"                          __vm_code[end]!=0x46)\n"
"                        end++;\n"
"                    vm_jit_compile(__vm_code,pc,end,bid);\n"
"                    if(__vm_jit_done[bid] && __vm_jit_table[bid]){\n"
"                        __vm_jit_table[bid]();\n"
"                        pc=end;\n"
"                        continue;\n"
"                    }\n"
"                }\n"
"            }\n"
"            break; }\n"
"\n"
"        case 0xF1: { /* JIT_COMPILE [u16 block_id] */\n"
"            uint16_t bid=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            if(bid<256 && !__vm_jit_done[bid]){\n"
"                int end=pc;\n"
"                while(end<(int)__vm_code_size &&\n"
"                      __vm_code[end]!=0x40 &&\n"
"                      __vm_code[end]!=0x41 &&\n"
"                      __vm_code[end]!=0x42 &&\n"
"                      __vm_code[end]!=0x44 &&\n"
"                      __vm_code[end]!=0x46)\n"
"                    end++;\n"
"                vm_jit_compile(__vm_code,pc,end,bid);\n"
"                if(__vm_jit_done[bid] && __vm_jit_table[bid]){\n"
"                    __vm_jit_table[bid]();\n"
"                    pc=end;\n"
"                    continue;\n"
"                }\n"
"            }\n"
"            break; }\n"
"\n"
"        case 0xF2: { /* JIT_CALL [u16 block_id] */\n"
"            uint16_t bid=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            if(bid<256 && __vm_jit_done[bid] && __vm_jit_table[bid]){\n"
"                __vm_jit_table[bid]();\n"
"            }\n"
"            break; }\n"
"\n"
"        case 0xF3: { /* TRACE_START [u16 block_id] */\n"
"            uint16_t bid=__vm_code[pc]|(__vm_code[pc+1]<<8); pc+=2;\n"
"            if(bid<256) __vm_profile[bid]+=10;\n"
"            break; }\n"
"\n"
"        case 0xF4: { /* TRACE_END */\n"
"            pc++;\n"
"            break; }\n"
"\n"
"        case 0xF5: { /* EVAL_ARITH — pop expr string, push int result */\n"
"            VmValue expr=vm_pop();\n"
"            const char *s=vm_to_str(&expr);\n"
"            int result=0;\n"
"            while(*s==' '||*s=='\\t')s++;\n"
"            /* Detect var=expr (assignment) BEFORE expansion */\n"
"            const char *eq=NULL;\n"
"            {const char *tp=s; while(*tp&&(isalpha((unsigned char)*tp)||*tp=='_'))tp++; while(*tp==' ')tp++; if(*tp=='='&&tp[1]!='=')eq=tp;}\n"
"            if(eq){\n"
"              char vname[128]; int vi=0; const char *tp=s;\n"
"              while(*tp&&(isalpha((unsigned char)*tp)||*tp=='_')&&vi<127)vname[vi++]=*tp++;\n"
"              vname[vi]=0;\n"
"              eq++; while(*eq==' ')eq++;\n"
"              char rhs[2048]; int ri=0; const char *rp=eq;\n"
"              while(*rp && ri<(int)sizeof(rhs)-1){\n"
"                if(*rp=='$'&&rp[1]){rp++;char vn[128];int vj=0;\n"
"                  if(*rp=='{'){rp++;while(*rp&&*rp!='}'&&vj<127)vn[vj++]=*rp++;if(*rp)rp++;}\n"
"                  else while(*rp&&(isalnum((unsigned char)*rp)||*rp=='_')&&vj<127)vn[vj++]=*rp++;\n"
"                  vn[vj]=0;const char *val=_getenv(vn);ri+=snprintf(rhs+ri,sizeof(rhs)-ri,\"%s\",val?val:\"0\");\n"
"                } else if(isalpha((unsigned char)*rp)||*rp=='_'){char vn[128];int vj=0;\n"
"                  while(*rp&&(isalnum((unsigned char)*rp)||*rp=='_')&&vj<127)vn[vj++]=*rp++;vn[vj]=0;\n"
"                  const char *val=_getenv(vn);ri+=snprintf(rhs+ri,sizeof(rhs)-ri,\"%s\",val?val:\"0\");\n"
"                } else rhs[ri++]=*rp++;\n"
"              }\n"
"              rhs[ri]=0;\n"
"              int a=0,b=0; char op='+'; const char *pp=rhs;\n"
"              int neg=0;if(*pp=='-'){neg=1;pp++;}\n"
"              while(*pp>='0'&&*pp<='9'){a=a*10+(*pp-'0');pp++;}\n"
"              if(neg)a=-a;while(*pp==' ')pp++;\n"
"              if(*pp&&*pp!=';'&&*pp!='\\n'){op=*pp++;if(op=='<'&&*pp=='='){pp++;op='l';}if(op=='>'&&*pp=='='){pp++;op='g';}while(*pp==' ')pp++;\n"
"                neg=0;if(*pp=='-'){neg=1;pp++;}\n"
"                while(*pp>='0'&&*pp<='9'){b=b*10+(*pp-'0');pp++;}if(neg)b=-b;\n"
"              }\n"
"              switch(op){case '+':result=a+b;break;case '-':result=a-b;break;case '*':result=a*b;break;case '/':if(b)result=a/b;break;case '%':if(b)result=a%b;break;case '<':result=(a<b);break;case '>':result=(a>b);break;case 'l':result=(a<=b);break;case 'g':result=(a>=b);break;case '=':result=(a==b);break;case '!':result=(a!=b);break;default:result=a;}\n"
"              char vs[32];snprintf(vs,sizeof(vs),\"%d\",result);_setenv(vname,vs,1);\n"
"            } else {\n"
"              /* Detect var++ / var-- BEFORE expansion */\n"
"              char vname[128]; int vi=0; const char *tp=s;\n"
"              while(*tp&&(isalpha((unsigned char)*tp)||*tp=='_')&&vi<127)vname[vi++]=*tp++;\n"
"              vname[vi]=0;while(*tp==' ')tp++;\n"
"              if(*tp=='+'&&tp[1]=='+'){const char *val=_getenv(vname);result=val?atoi(val):0;result++;char vs[32];snprintf(vs,sizeof(vs),\"%d\",result);_setenv(vname,vs,1);}\n"
"              else if(*tp=='-'&&tp[1]=='-'){const char *val=_getenv(vname);result=val?atoi(val):0;result--;char vs[32];snprintf(vs,sizeof(vs),\"%d\",result);_setenv(vname,vs,1);}\n"
"              else {\n"
"                char expanded[4096]; int ei=0; const char *p=s;\n"
"                while(*p&&ei<(int)sizeof(expanded)-1){\n"
"                  if(*p=='$'&&p[1]){p++;char vn[128];int vj=0;\n"
"                    if(*p=='{'){p++;while(*p&&*p!='}'&&vj<127)vn[vj++]=*p++;if(*p)p++;}\n"
"                    else while(*p&&(isalnum((unsigned char)*p)||*p=='_')&&vj<127)vn[vj++]=*p++;\n"
"                    vn[vj]=0;const char *val=_getenv(vn);ei+=snprintf(expanded+ei,sizeof(expanded)-ei,\"%s\",val?val:\"0\");\n"
"                  } else if(isalpha((unsigned char)*p)||*p=='_'){char vn[128];int vj=0;\n"
"                    while(*p&&(isalnum((unsigned char)*p)||*p=='_')&&vj<127)vn[vj++]=*p++;vn[vj]=0;\n"
"                    const char *val=_getenv(vn);ei+=snprintf(expanded+ei,sizeof(expanded)-ei,\"%s\",val?val:\"0\");\n"
"                  } else expanded[ei++]=*p++;\n"
"                }\n"
"                expanded[ei]=0;\n"
"                int a=0,b=0; char op='+'; const char *pp=expanded;\n"
"                int neg=0;if(*pp=='-'){neg=1;pp++;}\n"
"                while(*pp>='0'&&*pp<='9'){a=a*10+(*pp-'0');pp++;}\n"
"                if(neg)a=-a;while(*pp==' ')pp++;\n"
"                if(*pp&&*pp!=';'&&*pp!='\\n'){op=*pp++;if(op=='<'&&*pp=='='){pp++;op='l';}if(op=='>'&&*pp=='='){pp++;op='g';}while(*pp==' ')pp++;\n"
"                  neg=0;if(*pp=='-'){neg=1;pp++;}\n"
"                  while(*pp>='0'&&*pp<='9'){b=b*10+(*pp-'0');pp++;}if(neg)b=-b;\n"
"                }\n"
"                switch(op){case '+':result=a+b;break;case '-':result=a-b;break;case '*':result=a*b;break;case '/':if(b)result=a/b;break;case '%':if(b)result=a%b;break;case '<':result=(a<b);break;case '>':result=(a>b);break;case 'l':result=(a<=b);break;case 'g':result=(a>=b);break;case '=':result=(a==b);break;case '!':result=(a!=b);break;default:result=a;}\n"
"              }\n"
"            }\n"
"            vm_push(vm_int(result));\n"
"            vm_free(&expr);\n"
"            break; }\n"
"\n"
"        case 0xF7: { /* STR_TOUPPER */\n"
"            VmValue v=vm_pop(); const char *s=vm_to_str(&v);\n"
"            char *buf=_x_ma?_x_ma(strlen(s)+1):malloc(strlen(s)+1);\n"
"            int i; for(i=0;s[i];i++) buf[i]=toupper((unsigned char)s[i]); buf[i]=0;\n"
"            vm_push(vm_str(buf)); vm_free(&v);\n"
"            break; }\n"
"\n"
"        case 0xF8: { /* STR_TOLOWER */\n"
"            VmValue v=vm_pop(); const char *s=vm_to_str(&v);\n"
"            char *buf=_x_ma?_x_ma(strlen(s)+1):malloc(strlen(s)+1);\n"
"            int i; for(i=0;s[i];i++) buf[i]=tolower((unsigned char)s[i]); buf[i]=0;\n"
"            vm_push(vm_str(buf)); vm_free(&v);\n"
"            break; }\n"
"\n"
"        case 0xF9: { /* STR_SUBSTR — pop len, pop off, pop str, push substr */\n"
"            VmValue len_v=vm_pop(), off_v=vm_pop();\n"
"            VmValue str_v=vm_pop();\n"
"            const char *s=vm_to_str(&str_v);\n"
"            int off=vm_to_int(&off_v), len=vm_to_int(&len_v);\n"
"            int sl=strlen(s);\n"
"            if(off<0)off=0; if(off>sl)off=sl;\n"
"            if(len<0) len=sl-off; /* negative len = rest of string */\n"
"            if(off+len>sl) len=sl-off;\n"
"            char *buf=_x_ma?_x_ma(len+1):malloc(len+1);\n"
"            memcpy(buf,s+off,len); buf[len]=0;\n"
"            vm_push(vm_str(buf));\n"
"            vm_free(&str_v); vm_free(&off_v); vm_free(&len_v);\n"
"            break; }\n"
"\n"
"        case 0xFA: { /* STR_LEN */\n"
"            VmValue v=vm_pop(); const char *s=vm_to_str(&v);\n"
"            vm_push(vm_int((int)strlen(s))); vm_free(&v);\n"
"            break; }\n"
"\n"
"        case 0xFB: { /* COALESCE — pop b, pop a, push a if non-empty else b */\n"
"            VmValue b=vm_pop(), a=vm_pop();\n"
"            const char *sa=vm_to_str(&a);\n"
"            if(sa && sa[0]) { vm_push(a); vm_free(&b); }\n"
"            else { vm_push(b); vm_free(&a); }\n"
"            break; }\n"
"\n"
"        case 0xFC: { /* STRIP_PREFIX — pop pat, pop str, strip pat from front */\n"
"            VmValue pat=vm_pop(), s=vm_pop();\n"
"            const char *sv=vm_to_str(&s), *pv=vm_to_str(&pat);\n"
"            int pl=strlen(pv);\n"
"            if(strncmp(sv,pv,pl)==0) vm_push(vm_str(sv+pl));\n"
"            else vm_push(vm_str(sv));\n"
"            vm_free(&s); vm_free(&pat);\n"
"            break; }\n"
"\n"
"        case 0xFD: { /* STRIP_SUFFIX — pop pat, pop str, strip pat from end */\n"
"            VmValue pat=vm_pop(), s=vm_pop();\n"
"            const char *sv=vm_to_str(&s), *pv=vm_to_str(&pat);\n"
"            int sl=strlen(sv), pl=strlen(pv);\n"
"            if(pl>0 && sl>=pl && strcmp(sv+sl-pl,pv)==0){\n"
"              char *buf=_x_ma?_x_ma(sl-pl+1):malloc(sl-pl+1);\n"
"              memcpy(buf,sv,sl-pl); buf[sl-pl]=0;\n"
"              vm_push(vm_str(buf));\n"
"            } else vm_push(vm_str(sv));\n"
"            vm_free(&s); vm_free(&pat);\n"
"            break; }\n"
"\n"
"        case 0xFE: { /* ALL_ARGS — push all positional params space-joined */\n"
"            char buf[2048]; buf[0]=0; int bi=0;\n"
"            const char *ac=_getenv(\"__sh_argc\");\n"
"            int aci=ac?atoi(ac):0;\n"
"            for(int ai=1; ai<=aci && ai<=9; ai++){\n"
"              char an[4]; snprintf(an,sizeof(an),\"%d\",ai);\n"
"              const char *av=_getenv(an);\n"
"              if(av){\n"
"                if(bi>0) buf[bi++]=' ';\n"
"                int al=strlen(av);\n"
"                if(bi+al<(int)sizeof(buf)-1){memcpy(buf+bi,av,al);bi+=al;}\n"
"              }\n"
"            }\n"
"            buf[bi]=0;\n"
"            vm_push(vm_str(buf));\n"
"            break; }\n"
"\n"
"        default:\n"
"            /* Unknown opcode — halt with decoy computation */\n"
"            __vm_decoy(op);\n"
"            fprintf(stderr,\"VM: unknown opcode 0x%02x at pc=%u\\n\",op,pc-1);\n"
"            return 1;\n"
"        }\n"
"        /* End of inner switch */\n"
"        break;\n"
"        default: /* unreachable flattened state */\n"
"            __vm_decoy(__vm_state);\n"
"            break;\n"
"        }\n"
"        /* End of flattened dispatch */\n"
"        }\n"
"    }\n"
"    return 0;\n"
"}\n"
;

void emit_vm_runtime(FILE *out){
    fprintf(out, "%s", VM_RUNTIME);
}

void emit_vm_const_pool(FILE *out, const char **consts, int nconsts){
    fprintf(out, "static const char *__vm_const_data[] = {\n");
    for(int i=0; i<nconsts; i++){
        /* Escape for C string literal */
        fprintf(out, "    \"");
        for(const char *c = consts[i]; c && *c; c++){
            if(*c=='"') fprintf(out,"\\\"");
            else if(*c=='\\') fprintf(out,"\\\\");
            else if(*c=='\n') fprintf(out,"\\n");
            else if(*c=='\t') fprintf(out,"\\t");
            else if(*c=='\r') fprintf(out,"\\r");
            else fprintf(out,"%c",*c);
        }
        fprintf(out, "\",\n");
    }
    fprintf(out, "    NULL\n};\n");
    fprintf(out, "#define __VM_NCONSTS %d\n", nconsts);
}

void emit_vm_code(FILE *out, const uint8_t *code, int len){
    /* XOR-encode bytecode to prevent trivial extraction */
    fprintf(out, "static uint8_t __vm_code_encoded[] = {\n");
    for(int i=0; i<len; i++){
        if(i%16==0) fprintf(out, "    ");
        fprintf(out, "0x%02x", code[i] ^ 0x5A);
        if(i<len-1) fprintf(out, ",");
        if(i%16==15 || i==len-1) fprintf(out, "\n");
    }
    fprintf(out, "};\n");
    fprintf(out, "#define __VM_CODE_SIZE %d\n", len);
    /* Decode at runtime: XOR back */
    fprintf(out, "static uint8_t __vm_code_decoded[%d];\n", len);
    fprintf(out, "static void __vm_decode(void){\n");
    fprintf(out, "    for(int i=0;i<%d;i++) __vm_code_decoded[i]=__vm_code_encoded[i]^0x5A;\n", len);
    fprintf(out, "}\n");
}

void emit_vm_func_table(FILE *out, const VmFuncEntry *funcs, int nfuncs,
                        const char **const_pool){
    fprintf(out, "static VmFunc __vm_func_table[] = {\n");
    for(int i=0; i<nfuncs; i++){
        fprintf(out, "    {%d,%u,%d,%d},\n",
                funcs[i].name_idx, funcs[i].entry,
                funcs[i].nlocals, funcs[i].nargs);
    }
    fprintf(out, "    {0,0,0,0}\n};\n");
    fprintf(out, "#define __VM_NFUNCS %d\n", nfuncs);
}

void emit_vm_main(FILE *out){
    fprintf(out, "/* ---- VM entry point ---- */\n");
    fprintf(out, "int main(int argc, char **argv){\n");
    fprintf(out, "    setvbuf(stdout,NULL,_IONBF,0);\n");
    fprintf(out, "    __vm_consts = __vm_const_data;\n");
    fprintf(out, "    __vm_nconsts = __VM_NCONSTS;\n");
    fprintf(out, "    __vm_decode();\n");
    fprintf(out, "    __vm_code = __vm_code_decoded;\n");
    fprintf(out, "    __vm_code_size = __VM_CODE_SIZE;\n");
    fprintf(out, "    __vm_funcs = __vm_func_table;\n");
    fprintf(out, "    __vm_nfuncs = __VM_NFUNCS;\n");
    fprintf(out, "    /* Set $0-$9 from argv */\n");
    for(int i=0; i<10; i++){
        fprintf(out, "    if(argc>%d) setenv(\"%d\",argv[%d],1);\n", i, i, i);
    }
    fprintf(out, "    int rc = vm_run(0);\n");
    fprintf(out, "    return rc;\n");
    fprintf(out, "}\n");
}
